/*
 * generated by Xtext
 */
package de.uniol.inf.is.odysseus.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uniol.inf.is.odysseus.ui.internal.Pql2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Pql2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Pql2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Pql2Activator.getInstance().getInjector(Pql2Activator.DE_UNIOL_INF_IS_ODYSSEUS_PQL2);
	}
	
}
