/**
 * generated by Xtext 2.12.0
 */
package de.uniol.inf.is.odysseus.parser.cql2.cQL.impl;

import de.uniol.inf.is.odysseus.parser.cql2.cQL.CQLPackage;
import de.uniol.inf.is.odysseus.parser.cql2.cQL.Time;
import de.uniol.inf.is.odysseus.parser.cql2.cQL.TimebasedWindow;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Timebased Window</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.uniol.inf.is.odysseus.parser.cql2.cQL.impl.TimebasedWindowImpl#getSize <em>Size</em>}</li>
 *   <li>{@link de.uniol.inf.is.odysseus.parser.cql2.cQL.impl.TimebasedWindowImpl#getUnit <em>Unit</em>}</li>
 *   <li>{@link de.uniol.inf.is.odysseus.parser.cql2.cQL.impl.TimebasedWindowImpl#getAdvance_size <em>Advance size</em>}</li>
 *   <li>{@link de.uniol.inf.is.odysseus.parser.cql2.cQL.impl.TimebasedWindowImpl#getAdvance_unit <em>Advance unit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TimebasedWindowImpl extends WindowOperatorImpl implements TimebasedWindow
{
  /**
   * The default value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected static final int SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected int size = SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getUnit() <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnit()
   * @generated
   * @ordered
   */
  protected static final Time UNIT_EDEFAULT = Time.NULL;

  /**
   * The cached value of the '{@link #getUnit() <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUnit()
   * @generated
   * @ordered
   */
  protected Time unit = UNIT_EDEFAULT;

  /**
   * The default value of the '{@link #getAdvance_size() <em>Advance size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdvance_size()
   * @generated
   * @ordered
   */
  protected static final int ADVANCE_SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAdvance_size() <em>Advance size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdvance_size()
   * @generated
   * @ordered
   */
  protected int advance_size = ADVANCE_SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getAdvance_unit() <em>Advance unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdvance_unit()
   * @generated
   * @ordered
   */
  protected static final Time ADVANCE_UNIT_EDEFAULT = Time.NULL;

  /**
   * The cached value of the '{@link #getAdvance_unit() <em>Advance unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdvance_unit()
   * @generated
   * @ordered
   */
  protected Time advance_unit = ADVANCE_UNIT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TimebasedWindowImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CQLPackage.Literals.TIMEBASED_WINDOW;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSize()
  {
    return size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSize(int newSize)
  {
    int oldSize = size;
    size = newSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CQLPackage.TIMEBASED_WINDOW__SIZE, oldSize, size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Time getUnit()
  {
    return unit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnit(Time newUnit)
  {
    Time oldUnit = unit;
    unit = newUnit == null ? UNIT_EDEFAULT : newUnit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CQLPackage.TIMEBASED_WINDOW__UNIT, oldUnit, unit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getAdvance_size()
  {
    return advance_size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdvance_size(int newAdvance_size)
  {
    int oldAdvance_size = advance_size;
    advance_size = newAdvance_size;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CQLPackage.TIMEBASED_WINDOW__ADVANCE_SIZE, oldAdvance_size, advance_size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Time getAdvance_unit()
  {
    return advance_unit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdvance_unit(Time newAdvance_unit)
  {
    Time oldAdvance_unit = advance_unit;
    advance_unit = newAdvance_unit == null ? ADVANCE_UNIT_EDEFAULT : newAdvance_unit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CQLPackage.TIMEBASED_WINDOW__ADVANCE_UNIT, oldAdvance_unit, advance_unit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CQLPackage.TIMEBASED_WINDOW__SIZE:
        return getSize();
      case CQLPackage.TIMEBASED_WINDOW__UNIT:
        return getUnit();
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_SIZE:
        return getAdvance_size();
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_UNIT:
        return getAdvance_unit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CQLPackage.TIMEBASED_WINDOW__SIZE:
        setSize((Integer)newValue);
        return;
      case CQLPackage.TIMEBASED_WINDOW__UNIT:
        setUnit((Time)newValue);
        return;
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_SIZE:
        setAdvance_size((Integer)newValue);
        return;
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_UNIT:
        setAdvance_unit((Time)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CQLPackage.TIMEBASED_WINDOW__SIZE:
        setSize(SIZE_EDEFAULT);
        return;
      case CQLPackage.TIMEBASED_WINDOW__UNIT:
        setUnit(UNIT_EDEFAULT);
        return;
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_SIZE:
        setAdvance_size(ADVANCE_SIZE_EDEFAULT);
        return;
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_UNIT:
        setAdvance_unit(ADVANCE_UNIT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CQLPackage.TIMEBASED_WINDOW__SIZE:
        return size != SIZE_EDEFAULT;
      case CQLPackage.TIMEBASED_WINDOW__UNIT:
        return unit != UNIT_EDEFAULT;
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_SIZE:
        return advance_size != ADVANCE_SIZE_EDEFAULT;
      case CQLPackage.TIMEBASED_WINDOW__ADVANCE_UNIT:
        return advance_unit != ADVANCE_UNIT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (size: ");
    result.append(size);
    result.append(", unit: ");
    result.append(unit);
    result.append(", advance_size: ");
    result.append(advance_size);
    result.append(", advance_unit: ");
    result.append(advance_unit);
    result.append(')');
    return result.toString();
  }

} //TimebasedWindowImpl
