/* Generated By:JJTree: Do not edit this line. ASTBrokerSelectInto.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package de.uniol.inf.is.odysseus.parser.cql.parser;

public class ASTBrokerSelectInto extends SimpleNode {
  public ASTBrokerSelectInto(int id) {
    super(id);
  }

  public ASTBrokerSelectInto(NewSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(NewSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d121cbc14dd747dba9163299f71bd862 (do not edit this line) */
