/* Generated By:JJTree: Do not edit this line. ASTInPredicate.java */

package de.uniol.inf.is.odysseus.parser.cql.parser;

import de.uniol.inf.is.odysseus.sourcedescription.sdf.predicate.SDFCompareOperator;
import de.uniol.inf.is.odysseus.sourcedescription.sdf.predicate.SDFCompareOperatorFactory;
import de.uniol.inf.is.odysseus.sourcedescription.sdf.vocabulary.SDFPredicates;

public class ASTInPredicate extends AbstractQuantificationPredicate {
	public ASTInPredicate(int id) {
		super(id);
	}

	public ASTInPredicate(NewSQLParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(NewSQLParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public ASTComplexSelectStatement getQuery() {
		return (ASTComplexSelectStatement) jjtGetChild(1);
	}

	public SDFCompareOperator getCompareOperator() {
		return SDFCompareOperatorFactory.getCompareOperator(SDFPredicates.Equal);
	}

	public ASTTuple getTuple() {
		return (ASTTuple) jjtGetChild(0);
	}
}
