/* Generated By:JJTree: Do not edit this line. ASTSpatialCompareOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package de.uniol.inf.is.odysseus.parser.cql.parser;

public class ASTSpatialCompareOperator extends SimpleNode {
	String operator;

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		if (operator.equals("=")) {
			this.operator = "==";
			return;
		}
		if (operator.equals("<>")) {
			this.operator = "!=";
			return;
		}
		this.operator = operator;
	}
	
	public ASTSpatialCompareOperator(int id) {
    super(id);
  }

  public ASTSpatialCompareOperator(NewSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(NewSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
	public String toString() {
		return this.operator;
	}
}
/* JavaCC - OriginalChecksum=0a0676b85fd80251b04cb90fb24339d9 (do not edit this line) */
