package de.uniol.inf.is.odysseus.wrapper.json;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.UnknownHostException;
import java.nio.ByteBuffer;
import java.util.Iterator;
import java.util.Map;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.json.JSONTokener;

import de.uniol.inf.is.odysseus.core.collection.KeyValueObject;
import de.uniol.inf.is.odysseus.core.datahandler.IDataHandler;
import de.uniol.inf.is.odysseus.core.metadata.IMetaAttribute;
import de.uniol.inf.is.odysseus.core.physicaloperator.ITransferHandler;
import de.uniol.inf.is.odysseus.core.physicaloperator.access.protocol.AbstractProtocolHandler;
import de.uniol.inf.is.odysseus.core.physicaloperator.access.protocol.IProtocolHandler;
import de.uniol.inf.is.odysseus.core.physicaloperator.access.transport.IAccessPattern;
import de.uniol.inf.is.odysseus.core.physicaloperator.access.transport.ITransportDirection;
import de.uniol.inf.is.odysseus.core.physicaloperator.access.transport.ITransportHandler;

public class JSONProtocolHandler extends
		AbstractProtocolHandler<KeyValueObject<? extends IMetaAttribute>> {

	protected BufferedReader reader;

	@Override
	public void open() throws UnknownHostException, IOException {
		getTransportHandler().open();
		reader = new BufferedReader(new InputStreamReader(getTransportHandler()
				.getInputStream()));
	}

	@Override
	public void close() throws IOException {
		reader.close();
		getTransportHandler().close();
	}

	@Override
	public boolean hasNext() throws IOException {
		return true;
	}

	@Override
	public KeyValueObject<? extends IMetaAttribute> getNext()
			throws IOException {
		// ReadInput
		KeyValueObject<IMetaAttribute> out = null;
		JSONObject object = null;
		String nextObject = readNextObject(reader);
		out = new KeyValueObject<>();
		try {
			if (nextObject != null){
				// Replace not readable token in JSONTokener
				nextObject.replace("\n", " ").replace("\r", " ");
				object = new JSONObject(new JSONTokener(nextObject));
			}
		} catch (JSONException e) {
			throw new IOException(e);
		}
		// KeyValueObject Creation
		try {
			convert(object, out, "");
		} catch (JSONException e) {
			throw new IOException(e);
		}
		return out;
	}

	static public String readNextObject(BufferedReader reader) {
		StringBuffer object = new StringBuffer();
		int openBrackets = 0;
		boolean foundObject = false;
		try {
			String input = null;
			while ((input = reader.readLine()) != null) {
				char[] line = input.toCharArray();
				object.append(line);
				for (char c : line) {
					if (c == '{') {
						openBrackets++;
						foundObject = true;
					} else if (c == '}') {
						openBrackets--;
					}
				}
				if (openBrackets == 0 && foundObject) {
					return object.toString();
				}
			}
		} catch (IOException e) {

		}
		return null;
	}

	static public void convert(JSONObject object,
			KeyValueObject<IMetaAttribute> out, String path)
			throws IOException, JSONException {
		@SuppressWarnings("unchecked")
		Iterator<String> names = object.keys();
		while (names.hasNext()) {
			String key = names.next();
			Object value = null;
			value = object.get(key);
			if (value instanceof JSONObject) {
				StringBuffer newPath = new StringBuffer(path);
				newPath.append(key).append(".");
				convert((JSONObject) value, out, newPath.toString());
			} else if (value instanceof JSONArray) {
				JSONArray elements = (JSONArray) value;
				convert(elements, out, key, path);
			} else {
				out.setAttribute(path + key, value);
			}
		}
	}

	static public void convert(JSONArray elements,
			KeyValueObject<IMetaAttribute> out, String key, String path)
			throws IOException, JSONException {
		for (int i = 0; i < elements.length(); i++) {
			Object arrayElement = elements.get(i);
			StringBuffer newPath = new StringBuffer(path);
			newPath.append(key).append("[").append(i).append("]").append(".");
			if (arrayElement instanceof JSONObject) {
				convert((JSONObject) arrayElement, out, newPath.toString());
			} else if (arrayElement instanceof JSONArray) {
				convert((JSONArray) arrayElement, out, key, newPath.toString());
			} else {
				out.setAttribute(newPath.toString(), arrayElement);
			}
		}
	}

	@Override
	public void write(KeyValueObject<? extends IMetaAttribute> object)
			throws IOException {
		throw new IllegalArgumentException("Currently not implemented");
	}

	@Override
	public IProtocolHandler<KeyValueObject<? extends IMetaAttribute>> createInstance(
			ITransportDirection direction, IAccessPattern access,
			Map<String, String> options,
			IDataHandler<KeyValueObject<? extends IMetaAttribute>> dataHandler,
			ITransferHandler<KeyValueObject<? extends IMetaAttribute>> transfer) {
		JSONProtocolHandler instance = new JSONProtocolHandler();
		instance.setOptionsMap(options);
		instance.setDataHandler(dataHandler);
		instance.setTransfer(transfer);
		return instance;
	}

	@Override
	public String getName() {
		return "JSON";
	}

	public static void main(String[] args) throws JSONException, IOException {
		String[] tests = {
				"{" + "\"firstName\": \"John\"," + "\"lastName\": \"Smith\","
						+ "\"age\": 25," + "\"address\": {"
						+ "\"streetAddress\": \"21 2nd Street\","
						+ "\"city\": \"New York\"," + "\"state\": \"NY\","
						+ "\"postalCode\": \"10021\"" + "},"
						+ "\"phoneNumber\": [" + "{" + "\"type\": \"home\","
						+ "\"number\": \"212 555-1234\"" + "}," + "{"
						+ "\"type\": \"fax\"," + "\"number\": \"646 555-4567\""
						+ "}" + "]" + "}",
				"{"
						+ "  \"data\": ["
						+ "    {"
						+ "      \"id\": \"40796308305_10152568266718306\","
						+ "      \"from\": {"
						+ "        \"name\": \"V-nina Igi\","
						+ "        \"id\": \"100003096473420\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"Hallo Coca-Cola team ich hätte da mal eine idee\nWie ihr eure neuen Coca Cola Ettiketten verzieren könntet \n\nDie ideen das sind nur Beispiele\n\nDer neue superheld 2013 ist\n ............\n\nGermanys next topmodel 2013 ist\n .............\n\nMein neuer lover ist\n\n ............\n\n (bff)\n Du bist meine abf\n ...........\n\nLasst auch andere leute davon wiesen und fragt was für Ideen sie haben\n\nBitte schreibt auch mal vanessa weil vanessa hab ich noch nicht gesehen\n\nUnd wenn ihr die idee verwirklich könnt ihr dan drauf schreiben Wer die idee hatte das heißt vanessa ignasiak oder überhaupt das ich irgendwo mitspiele z.B. In einem Coca-Cola werbespot\n\nAch übrigens ich bin 11 jahre alt meine Hobbys sind :\nReiten,tennis,handball,\nFussball,Volleyball,malen,\nideen ausdenken,nähen,mit freunden treffen\n\nLg eure vanessa\n:-);-):-o:-D:-P\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568266718306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568266718306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T07:42:03+0000\","
						+ "      \"updated_time\": \"2013-07-31T07:42:03+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_525183100885979\","
						+ "      \"from\": {"
						+ "        \"name\": \"Eli Borisova\","
						+ "        \"id\": \"100001828823358\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"picture\": \"https://fbcdn-sphotos-d-a.akamaihd.net/hphotos-ak-ash4/q71/s480x480/1003867_525183100885979_655995704_n.jpg\","
						+ "      \"link\": \"https://www.facebook.com/photo.php?fbid=525183100885979&set=o.40796308305&type=1\","
						+ "      \"icon\": \"https://fbstatic-a.akamaihd.net/rsrc.php/v2/yz/r/StEh3RhPvjk.gif\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/525183100885979\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/525183100885979\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"photo\","
						+ "      \"object_id\": \"525183100885979\","
						+ "      \"application\": {"
						+ "        \"name\": \"Photos\","
						+ "        \"id\": \"2305272732\""
						+ "      },"
						+ "      \"created_time\": \"2013-07-31T07:38:12+0000\","
						+ "      \"updated_time\": \"2013-07-31T07:38:12+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568258518306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Vanakkam Sathish\","
						+ "        \"id\": \"100002474240324\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"DEAR SIR I AM SATHISH FROM TRICHY, I PLACED 1000 NO NIMBU FRESH TO BE SUPPLIED TO A GRAND FUNCTION OF BHEL TO BE ON 2ND NEXT MONTH S UR PEOPLE COMMITTED THAT THEY CAN SUPPLY BUT SUDDENLY THEY R SAYING THAT THEY CANT. I HAD RECEIVED PURCHASE ORDER i dont know what to do other than running of the place as it is serious problem pls help me in this regard\nmy mobile no.9092058991\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568258518306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568258518306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T07:34:34+0000\","
						+ "      \"updated_time\": \"2013-07-31T07:34:34+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10200900270423124\","
						+ "      \"from\": {"
						+ "        \"name\": \"Sameer Sheikh\","
						+ "        \"id\": \"1656007404\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"http://blog.travelpod.com/travel-blog-entries/academybotany/1/1375272774/tpod.html\","
						+ "      \"picture\": \"https://fbexternal-a.akamaihd.net/safe_image.php?d=AQA4FP-MwcM0y8rF&w=154&h=154&url=http%3A%2F%2Fimages.travelpod.com%2Fusers%2Facademybotany%2Fthumbnail.xlarge.1.1375272774.accommodation-in-auckland.jpg\","
						+ "      \"link\": \"http://blog.travelpod.com/travel-blog-entries/academybotany/1/1375272774/tpod.html\","
						+ "      \"name\": \"Live Amazing Life of Auckland - Auckland, New Zealand Travel Blog\","
						+ "      \"caption\": \"blog.travelpod.com\","
						+ "      \"description\": \"Live Amazing Life of Auckland: Read the story and see 4 photos of a visit to Auckland, New Zealand by TravelPod member academybotany\","
						+ "      \"icon\": \"https://fbstatic-a.akamaihd.net/rsrc.php/v2/yD/r/aS8ecmYRys0.gif\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10200900270423124\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10200900270423124\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"link\","
						+ "      \"created_time\": \"2013-07-31T07:25:09+0000\","
						+ "      \"updated_time\": \"2013-07-31T07:25:09+0000\","
						+ "      \"likes\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"name\": \"Sameer Sheikh\","
						+ "            \"id\": \"1656007404\""
						+ "          }"
						+ "        ],"
						+ "        \"count\": 1"
						+ "      }"
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568240448306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Ho Muxo Natural\","
						+ "        \"id\": \"100006237453911\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"Pepsi cung ngon ma ,,,,\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568240448306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568240448306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T07:17:44+0000\","
						+ "      \"updated_time\": \"2013-07-31T07:17:44+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568230373306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Ayoola Dammy Gcfr\","
						+ "        \"id\": \"1648768159\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"Pls share ...\r\nAS I LOVE YOU REACH\r\nNothing dey totoli my belle pass you! As I dey\r\ntink your matter, my head dey swell with love.\r\nAh! I love you pieces, true talk, I love you\r\nscatter! As I take sidom gidigba, nothing fit\r\nshake me, everything dey under my power. Love\r\nna my nature, mercy be my own… but as I dey\r\nlook you, na with mercy for my eye. Ah! you too\r\ndey precious to me, you weh I sidom create. You\r\nknow ehn, from all the things wey my hand\r\narrange, na you blow my head pass. I kon tink\r\nam say the only creature wey go see wetin I be\r\nna you, the only creature wey I go comot cover\r\ncloth show myself, na you; the only creature\r\nweh go look inside my secret na you! Infact, I\r\nswear by myself say if you torchlight me, you go\r\nfind me!\r\n…\r\nMy love, you know all them those big giant\r\nangels? Them sidom my front every day, them\r\ndey wonder as I take be. Every time, them they\r\nshout glory! glory o! glory o o! Them they shout\r\nbecause them just dey see different things wen\r\ndey no go fit understand… na me create dem, I\r\nlike dem o, but na you I choose…my love, I\r\nleave everything wey I create, choose you.\r\n…\r\nIf you go comot yourself from the plenty noise,\r\nif you go near me; if your eye go just dey look\r\nmy matter, if your heart go just sempe. My love,\r\nmy precious love; if you go do these things, I\r\nswear by myself say you go enter me, share my\r\nglory!\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568230373306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568230373306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T07:05:19+0000\","
						+ "      \"updated_time\": \"2013-07-31T07:05:19+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568224203306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Victor Marrugo Pajaro\","
						+ "        \"id\": \"100001632724942\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"quiero saber cual es la nueva promocion cocacola????????????\ncompre una cocacola de tapa verde y por debajo dise vajilla quisiera saber si es que me gane una bajilla o que o en donde la reclamo????????????????????????????\n\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568224203306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568224203306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T06:57:50+0000\","
						+ "      \"updated_time\": \"2013-07-31T06:57:50+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568220423306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Renan Ferreira de Assis\","
						+ "        \"id\": \"100004871769416\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"coca-cola eh a melhor q tem.\r\nQUANDO FOR COMPRAR REFRIGERANTE PD COCA\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568220423306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568220423306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T06:53:01+0000\","
						+ "      \"updated_time\": \"2013-07-31T06:53:01+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568220258306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Nicolle Isabelle\","
						+ "        \"id\": \"1391274871\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"tres tres decu on peut meme pas recevoir notre bon de reduction c'est une PUBLICITE MENSONGERE je vais envoyer un courrier \","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568220258306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568220258306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T06:52:54+0000\","
						+ "      \"updated_time\": \"2013-07-31T06:53:59+0000\","
						+ "      \"likes\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"name\": \"Nicolle Isabelle\","
						+ "            \"id\": \"1391274871\""
						+ "          }"
						+ "        ],"
						+ "        \"count\": 1"
						+ "      },"
						+ "      \"comments\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"id\": \"10152568220258306_28823272\","
						+ "            \"from\": {"
						+ "              \"name\": \"Nicolle Isabelle\","
						+ "              \"id\": \"1391274871\""
						+ "            },"
						+ "            \"message\": \"meme sur mon portable tu tenregistre mais sa ne valide pas\","
						+ "            \"can_remove\": false,"
						+ "            \"created_time\": \"2013-07-31T06:53:28+0000\","
						+ "            \"like_count\": 0,"
						+ "            \"user_likes\": false"
						+ "          },"
						+ "          {"
						+ "            \"id\": \"10152568220258306_28823276\","
						+ "            \"from\": {"
						+ "              \"name\": \"Nicolle Isabelle\","
						+ "              \"id\": \"1391274871\""
						+ "            },"
						+ "            \"message\": \"dans ces cas on ne met pas la publicité sur ce site\","
						+ "            \"can_remove\": false,"
						+ "            \"created_time\": \"2013-07-31T06:53:59+0000\","
						+ "            \"like_count\": 0,"
						+ "            \"user_likes\": false"
						+ "          }"
						+ "        ],"
						+ "        \"paging\": {"
						+ "          \"cursors\": {"
						+ "            \"after\": \"Mg==\","
						+ "            \"before\": \"MQ==\""
						+ "          }"
						+ "        }"
						+ "      }"
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568199598306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Chrispine Wadanda\","
						+ "        \"id\": \"100001854022709\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"I'll be grateful if I get social support from the Coca Cola family for my local club. my name is Chrispine Wadanda; my club is (visit on face-book)nyams united f.c\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568199598306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568199598306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T06:26:21+0000\","
						+ "      \"updated_time\": \"2013-07-31T06:26:21+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568193478306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Elvia Calan\","
						+ "        \"id\": \"100004979504137\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"M gustas yo t tomo n te dejo, amo mi cocacola\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568193478306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568193478306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"application\": {"
						+ "        \"name\": \"Facebook for Every Phone\","
						+ "        \"id\": \"139682082719810\""
						+ "      },"
						+ "      \"created_time\": \"2013-07-31T06:18:42+0000\","
						+ "      \"updated_time\": \"2013-07-31T06:18:42+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568160543306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Ekalak Promchart\","
						+ "        \"id\": \"622483590\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"????????????? (?????) ???????????????????? ?????????????????????? ??????????? ?????????????? ???????????? ???????????? CSR ????? ????????????????? ???????????????????????????????\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568160543306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568160543306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T05:41:43+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:41:43+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568157118306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Charlotte Præst Andersen\","
						+ "        \"id\": \"1485292265\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"Uhhh hvor har de mange flere sjove og søde flasker i Østrig og Tyskland - Fandt en flaske 1 L med min søns navn - André - Håber der også kommer flere sjove og søde til Danmark \","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568157118306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568157118306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T05:38:16+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:38:16+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568153393306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Freda Dawson\","
						+ "        \"id\": \"1536592169\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"Coca-Cola is so good, it doesn't make any sense. It is my most favorite drink in the WORLD! WOOT! WOOT!\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568153393306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568153393306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T05:34:42+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:34:42+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568144828306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Flakis Morales\","
						+ "        \"id\": \"100003528615718\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"La verdad no hay como la coca llevo un buen sin mi marido y vivo bien pero sin la coca no puedo ni un dia\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568144828306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568144828306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"application\": {"
						+ "        \"name\": \"Facebook for Every Phone\","
						+ "        \"id\": \"139682082719810\""
						+ "      },"
						+ "      \"created_time\": \"2013-07-31T05:26:27+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:26:27+0000\","
						+ "      \"likes\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"name\": \"Zendy Vianey\","
						+ "            \"id\": \"100002512146693\""
						+ "          }"
						+ "        ],"
						+ "        \"count\": 1"
						+ "      }"
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568130718306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Mar Pereyra\","
						+ "        \"id\": \"1468209793\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"aguante pepsi! \","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568130718306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568130718306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T05:16:25+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:16:25+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568126703306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Juan Carlos G\","
						+ "        \"id\": \"100001740130176\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"me gsuta coca cola taigana iron maiden a guatemala ¡¡¡¡¡ XD ¡¡¡¡ \n\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568126703306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568126703306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T05:14:25+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:14:25+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568107358306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Eduardo Murillo\","
						+ "        \"id\": \"1214368259\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"I like to drink coke, It's the better refreshment for me \","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568107358306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568107358306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T05:02:24+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:02:24+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568105323306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Marianitha Valdez\","
						+ "        \"id\": \"100004966441343\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"CADA DIA SOY MAS ADICTA A ELLA\n<3 <3\n\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568105323306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568105323306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T05:00:38+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:00:38+0000\","
						+ "      \"likes\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"name\": \"Iris Salazar Diaz\","
						+ "            \"id\": \"1308558800\""
						+ "          }"
						+ "        ],"
						+ "        \"count\": 1"
						+ "      }"
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568095578306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Fernando Rojas Muñoz\","
						+ "        \"id\": \"100000200180478\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"A todas las personas que ponen cosas negativas de coca cola...\nsinceramente que les interesa si tomo mucha o poca coca cola es mi gusto, es mi bebida.\ny muy por encima de que ustedes digan que hace daño es mi gusto y la tomo a como yo quiera y considere que esta bien,\nustedes hacen mas cosas dañinas en su día a día que todo lo que propone coca cola en su publicidad, si se dan cuenta en ningún comercial te dicen que tomes coca cola... solo te invitan a que ayudes a crear un mundo mejor, un lugar mas sano, mas divertido para vivir, con una actitud mas positiva de la que tienes actualmente... ocupas tu tiempo queriendo hacer menos a una marca, haciendo comentarios negativos de una bebida, y poniendo en duda la salud de la gente... en vez de ocuparte en ayudar a las personas, donar en el cajero, dando una ayuda a las personas que lo necesiten o un aventón a alguien, pero en vez de esto no haces nada que ayude a sentirte mejor. \nrecuerda tú gente frustrada que pone esos comentarios, quieres limpiar la casa de los demás sin ver que es lo que esta tirado en la tuya, empieza por cambiar tu actitud y cuando cambies tu manera de pensar empezaras a ver con el corazón y darte cuenta que no importa si tomas o no coca cola, las forma en que coca cola quiere que vivas son mas importantes de lo que piensas la tomes o no.\n\nrecuerda... no critiques, mejor ayuda. \","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568095578306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568095578306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T04:52:46+0000\","
						+ "      \"updated_time\": \"2013-07-31T05:01:02+0000\","
						+ "      \"likes\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"name\": \"Luisa Fernanda Regalado\","
						+ "            \"id\": \"1830104100\""
						+ "          },"
						+ "          {"
						+ "            \"name\": \"Roy Andrade Ocampo\","
						+ "            \"id\": \"1665249558\""
						+ "          },"
						+ "          {"
						+ "            \"name\": \"Fernando Rojas Muñoz\","
						+ "            \"id\": \"100000200180478\""
						+ "          }"
						+ "        ],"
						+ "        \"count\": 3"
						+ "      },"
						+ "      \"comments\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"id\": \"10152568095578306_28822112\","
						+ "            \"from\": {"
						+ "              \"name\": \"Roy Andrade Ocampo\","
						+ "              \"id\": \"1665249558\""
						+ "            },"
						+ "            \"message\": \":3 YA TE AMO!!!\","
						+ "            \"can_remove\": false,"
						+ "            \"created_time\": \"2013-07-31T05:01:02+0000\","
						+ "            \"like_count\": 2,"
						+ "            \"user_likes\": false"
						+ "          }"
						+ "        ],"
						+ "        \"paging\": {"
						+ "          \"cursors\": {"
						+ "            \"after\": \"MQ==\","
						+ "            \"before\": \"MQ==\""
						+ "          }"
						+ "        }"
						+ "      }"
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568084408306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Chiwawa TanwaGuitarist Moowaan\","
						+ "        \"id\": \"1705018222\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"?????? ??????????????????????????????????????????\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568084408306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568084408306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"application\": {"
						+ "        \"name\": \"Facebook for iPhone\","
						+ "        \"namespace\": \"fbiphone\","
						+ "        \"id\": \"6628568379\""
						+ "      },"
						+ "      \"created_time\": \"2013-07-31T04:42:22+0000\","
						+ "      \"updated_time\": \"2013-07-31T04:42:22+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_149038955297463\","
						+ "      \"from\": {"
						+ "        \"name\": \"Fernando Fernandez\","
						+ "        \"id\": \"100005740781257\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"picture\": \"https://fbexternal-a.akamaihd.net/safe_image.php?d=AQBM4fLmRZpVDxJe&w=130&h=130&url=http%3A%2F%2Fi1.ytimg.com%2Fvi%2FA1hdZYfhdew%2Fhqdefault.jpg%3Ffeature%3Dog\","
						+ "      \"link\": \"http://www.youtube.com/watch?v=A1hdZYfhdew&feature=youtu.be\","
						+ "      \"source\": \"http://www.youtube.com/v/A1hdZYfhdew?autohide=1&version=3&autoplay=1\","
						+ "      \"name\": \"como una bendicion cancion de antonio salazar charre\","
						+ "      \"caption\": \"www.youtube.com\","
						+ "      \"description\": \"canciones de antonio salazar charre\","
						+ "      \"icon\": \"https://fbstatic-a.akamaihd.net/rsrc.php/v2/yj/r/v2OnaTyTQZE.gif\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/149038955297463\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/149038955297463\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"video\","
						+ "      \"created_time\": \"2013-07-31T04:40:03+0000\","
						+ "      \"updated_time\": \"2013-07-31T04:40:03+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568074993306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Charles Rodrigues\","
						+ "        \"id\": \"100005105262147\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"COCA-COLA E LIXO PRA MIM!\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568074993306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568074993306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T04:31:55+0000\","
						+ "      \"updated_time\": \"2013-07-31T04:31:55+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568072573306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Muthu Samy\","
						+ "        \"id\": \"100001275492173\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"I am fan of coca cola\n\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568072573306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568072573306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"created_time\": \"2013-07-31T04:28:57+0000\","
						+ "      \"updated_time\": \"2013-07-31T04:28:57+0000\""
						+ "    },"
						+ "    {"
						+ "      \"id\": \"40796308305_10152568069203306\","
						+ "      \"from\": {"
						+ "        \"name\": \"Marcia Maria Oliveira Aquinno\","
						+ "        \"id\": \"100002963986372\""
						+ "      },"
						+ "      \"to\": {"
						+ "        \"data\": ["
						+ "          {"
						+ "            \"category\": \"Food/beverages\","
						+ "            \"name\": \"Coca-Cola\","
						+ "            \"id\": \"40796308305\""
						+ "          }"
						+ "        ]"
						+ "      },"
						+ "      \"message\": \"Coca cola tudo de bom!:*\","
						+ "      \"actions\": ["
						+ "        {"
						+ "          \"name\": \"Comment\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568069203306\""
						+ "        },"
						+ "        {"
						+ "          \"name\": \"Like\","
						+ "          \"link\": \"https://www.facebook.com/40796308305/posts/10152568069203306\""
						+ "        }"
						+ "      ],"
						+ "      \"privacy\": {"
						+ "        \"value\": \"\""
						+ "      },"
						+ "      \"type\": \"status\","
						+ "      \"application\": {"
						+ "        \"name\": \"Facebook for Every Phone\","
						+ "        \"id\": \"139682082719810\""
						+ "      },"
						+ "      \"created_time\": \"2013-07-31T04:24:52+0000\","
						+ "      \"updated_time\": \"2013-07-31T04:24:52+0000\""
						+ "    }"
						+ "  ],"
						+ "  \"paging\": {"
						+ "    \"previous\": \"https://graph.facebook.com/40796308305/feed?limit=25&since=1375256523\","
						+ "    \"next\": \"https://graph.facebook.com/40796308305/feed?limit=25&until=1375244691\""
						+ "  }" + "}" };
		for (String test : tests) {
			try {
				test = test.replace("\n", " ").replace("\r", " ");
				JSONObject object = new JSONObject(test);
				System.out.println("Trying to parse Object: " + object);
				KeyValueObject<IMetaAttribute> out = new KeyValueObject<>();
				convert(object, out, "");
				System.out.println("RESULT");
				System.out.println(out);
			} catch (Exception e) {
				e.printStackTrace();
			}
		}

	}

	@Override
	public void onConnect(ITransportHandler caller) {
		// TODO Auto-generated method stub

	}

	@Override
	public void onDisonnect(ITransportHandler caller) {
		// TODO Auto-generated method stub

	}

	@Override
	public void process(ByteBuffer message) {
		throw new RuntimeException("Not implemented yet");
	}
	
	@Override
	public void process(String[] message) {
		throw new RuntimeException("Not implemented yet");
	}

	@Override
	public boolean isSemanticallyEqualImpl(IProtocolHandler<?> o) {
		if(!(o instanceof JSONProtocolHandler)) {
			return false;
		} else {
			// the datahandler was already checked in the isSemanticallyEqual-Method of AbstracProtocolHandler
			return true;
		}
	}
}
