
package de.uniol.inf.is.odysseus.bpel.correlationservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.5
 * Mon Feb 15 16:18:07 CET 2010
 * Generated source version: 2.2.5
 * 
 */
 
public class CorrelationService_CorrelationServiceSOAP_Server{
	private Endpoint endPoint;
    private static String address = "http://127.0.0.1:9999/correlationService"; 

    public CorrelationService_CorrelationServiceSOAP_Server() throws Exception {
        Object implementor = new CorrelationServiceImpl();
        this.endPoint = Endpoint.publish(address, implementor);
    }
    
    public void stop (){
		this.endPoint.stop();
	}
}
