/*
 * generated by Xtext 2.12.0
 */
package de.uniol.inf.is.odysseus.iql.odl.parser.antlr;

import com.google.inject.Inject;
import de.uniol.inf.is.odysseus.iql.odl.parser.antlr.internal.InternalODLParser;
import de.uniol.inf.is.odysseus.iql.odl.services.ODLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ODLParser extends AbstractAntlrParser {

	@Inject
	private ODLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalODLParser createParser(XtextTokenStream stream) {
		return new InternalODLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ODLModel";
	}

	public ODLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ODLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
