
package de.uniol.inf.is.odysseus.generator.frequentitem.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebserviceServer", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebserviceServer {


    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetNameResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getNameRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getNameResponse")
    public StringResponse getName(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.BooleanResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isRunning", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.IsRunning")
    @ResponseWrapper(localName = "isRunningResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.IsRunningResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/isRunningRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/isRunningResponse")
    public BooleanResponse isRunning(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQueryBuildConfigurationNames", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetQueryBuildConfigurationNames")
    @ResponseWrapper(localName = "getQueryBuildConfigurationNamesResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetQueryBuildConfigurationNamesResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getQueryBuildConfigurationNamesRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getQueryBuildConfigurationNamesResponse")
    public StringListResponse getQueryBuildConfigurationNames(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredBufferPlacementStrategiesIDs", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetRegisteredBufferPlacementStrategiesIDs")
    @ResponseWrapper(localName = "getRegisteredBufferPlacementStrategiesIDsResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetRegisteredBufferPlacementStrategiesIDsResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getRegisteredBufferPlacementStrategiesIDsRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getRegisteredBufferPlacementStrategiesIDsResponse")
    public StringListResponse getRegisteredBufferPlacementStrategiesIDs(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredSchedulingStrategies", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetRegisteredSchedulingStrategies")
    @ResponseWrapper(localName = "getRegisteredSchedulingStrategiesResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetRegisteredSchedulingStrategiesResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getRegisteredSchedulingStrategiesRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getRegisteredSchedulingStrategiesResponse")
    public StringListResponse getRegisteredSchedulingStrategies(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentSchedulingStrategyID", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetCurrentSchedulingStrategyID")
    @ResponseWrapper(localName = "getCurrentSchedulingStrategyIDResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetCurrentSchedulingStrategyIDResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getCurrentSchedulingStrategyIDRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getCurrentSchedulingStrategyIDResponse")
    public StringResponse getCurrentSchedulingStrategyID(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param query
     * @param transformationconfig
     * @param parser
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.IntegerCollectionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addQuery", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.AddQuery")
    @ResponseWrapper(localName = "addQueryResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.AddQueryResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/addQueryRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/addQueryResponse")
    public IntegerCollectionResponse addQuery(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "parser", targetNamespace = "")
        String parser,
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "transformationconfig", targetNamespace = "")
        String transformationconfig);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringResponse
     */
    @WebMethod
    @WebResult(name = "securitytoken", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.LoginResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/loginRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/loginResponse")
    public StringResponse login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param queryID
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeQuery", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.RemoveQuery")
    @ResponseWrapper(localName = "removeQueryResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.RemoveQueryResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/removeQueryRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/removeQueryResponse")
    public Response removeQuery(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "queryID", targetNamespace = "")
        int queryID);

    /**
     * 
     * @param id
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.QueryResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLogicalQuery", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetLogicalQuery")
    @ResponseWrapper(localName = "getLogicalQueryResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetLogicalQueryResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getLogicalQueryRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getLogicalQueryResponse")
    public QueryResponse getLogicalQuery(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param queryId
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.SdfSchemaResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutputSchema", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetOutputSchema")
    @ResponseWrapper(localName = "getOutputSchemaResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetOutputSchemaResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getOutputSchemaRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getOutputSchemaResponse")
    public SdfSchemaResponse getOutputSchema(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "queryId", targetNamespace = "")
        int queryId);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSupportedQueryParsers", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetSupportedQueryParsers")
    @ResponseWrapper(localName = "getSupportedQueryParsersResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetSupportedQueryParsersResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getSupportedQueryParsersRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getSupportedQueryParsersResponse")
    public StringListResponse getSupportedQueryParsers(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param scheduler
     * @param schedulerStrategy
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setScheduler", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.SetScheduler")
    @ResponseWrapper(localName = "setSchedulerResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.SetSchedulerResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/setSchedulerRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/setSchedulerResponse")
    public Response setScheduler(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "scheduler", targetNamespace = "")
        String scheduler,
        @WebParam(name = "scheduler_strategy", targetNamespace = "")
        String schedulerStrategy);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.LogoutResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/logoutRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/logoutResponse")
    public Response logout(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param queryID
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startQuery", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StartQuery")
    @ResponseWrapper(localName = "startQueryResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StartQueryResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/startQueryRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/startQueryResponse")
    public Response startQuery(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "queryID", targetNamespace = "")
        int queryID);

    /**
     * 
     * @param queryID
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopQuery", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StopQuery")
    @ResponseWrapper(localName = "stopQueryResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StopQueryResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/stopQueryRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/stopQueryResponse")
    public Response stopQuery(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "queryID", targetNamespace = "")
        int queryID);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInstalledSources", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetInstalledSources")
    @ResponseWrapper(localName = "getInstalledSourcesResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetInstalledSourcesResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getInstalledSourcesRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getInstalledSourcesResponse")
    public StringListResponse getInstalledSources(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInstalledQueries", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetInstalledQueries")
    @ResponseWrapper(localName = "getInstalledQueriesResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetInstalledQueriesResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getInstalledQueriesRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getInstalledQueriesResponse")
    public StringListResponse getInstalledQueries(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param queryId
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.ConnectionInformationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConnectionInformation", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetConnectionInformation")
    @ResponseWrapper(localName = "getConnectionInformationResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetConnectionInformationResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getConnectionInformationRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getConnectionInformationResponse")
    public ConnectionInformationResponse getConnectionInformation(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken,
        @WebParam(name = "queryId", targetNamespace = "")
        int queryId);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.IntegerCollectionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLogicalQueryIds", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetLogicalQueryIds")
    @ResponseWrapper(localName = "getLogicalQueryIdsResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetLogicalQueryIdsResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getLogicalQueryIdsRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getLogicalQueryIdsResponse")
    public IntegerCollectionResponse getLogicalQueryIds(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startAllClosedQueries", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StartAllClosedQueries")
    @ResponseWrapper(localName = "startAllClosedQueriesResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StartAllClosedQueriesResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/startAllClosedQueriesRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/startAllClosedQueriesResponse")
    public Response startAllClosedQueries(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringListResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredSchedulers", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetRegisteredSchedulers")
    @ResponseWrapper(localName = "getRegisteredSchedulersResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetRegisteredSchedulersResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getRegisteredSchedulersRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getRegisteredSchedulersResponse")
    public StringListResponse getRegisteredSchedulers(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentSchedulerID", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetCurrentSchedulerID")
    @ResponseWrapper(localName = "getCurrentSchedulerIDResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetCurrentSchedulerIDResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getCurrentSchedulerIDRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getCurrentSchedulerIDResponse")
    public StringResponse getCurrentSchedulerID(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startExecution", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StartExecution")
    @ResponseWrapper(localName = "startExecutionResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StartExecutionResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/startExecutionRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/startExecutionResponse")
    public Response startExecution(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stopExecution", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StopExecution")
    @ResponseWrapper(localName = "stopExecutionResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StopExecutionResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/stopExecutionRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/stopExecutionResponse")
    public Response stopExecution(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.StringResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfos", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetInfos")
    @ResponseWrapper(localName = "getInfosResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetInfosResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getInfosRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getInfosResponse")
    public StringResponse getInfos(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

    /**
     * 
     * @param securitytoken
     * @return
     *     returns de.uniol.inf.is.odysseus.generator.frequentitem.webservice.SimpleGraph
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlan", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetPlan")
    @ResponseWrapper(localName = "getPlanResponse", targetNamespace = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/", className = "de.uniol.inf.is.odysseus.generator.frequentitem.webservice.GetPlanResponse")
    @Action(input = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getPlanRequest", output = "http://webservice.webserviceexecutor.executor.planmanagement.odysseus.is.inf.uniol.de/WebserviceServer/getPlanResponse")
    public SimpleGraph getPlan(
        @WebParam(name = "securitytoken", targetNamespace = "")
        String securitytoken);

}
