package de.uniol.inf.is.odysseus.filtering;

public enum HashConstants {
	GAIN_OLD_COVARIANCE, GAIN_NEW_COVARIANCE, ESTIMATE_OLD_MEASUREMENT, ESTIMATE_NEW_MEASUREMENT, ESTIMATE_GAIN, COVARIANCE_OLD_COVARIANCE, COVARIANCE_GAIN
}
