package de.uniol.inf.is.odysseus.rest2.server.events;

public enum ServerEventType {

	QUERY_ADDED, ERROR_EVENT, PLAN_MODIFICATION, SCHEDULER_MANAGER, EXECUTOR_COMMAND, COMPILER, SESSION, DATADICTIONARY, USER, QUERY, SCHEDULING;

}
