/* Generated By:JJTree: Do not edit this line. ASTOptions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniol.inf.is.odysseus.parser.cql.parser;

public
@SuppressWarnings("all")
class ASTOptions extends SimpleNode {
  public ASTOptions(int id) {
    super(id);
  }

  public ASTOptions(NewSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(NewSQLParserVisitor visitor, Object data) throws de.uniol.inf.is.odysseus.core.server.planmanagement.QueryParseException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9614bcd2b51e767048294bcc0fe34e3b (do not edit this line) */
