/*
 * Odysseus API
 * This is the API of the [Odysseus](https://odysseus.uni-oldenburg.de/) server.
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.uniol.inf.is.odysseus.rest2.client.api.auth;

import java.util.List;
import java.util.Map;

import de.uniol.inf.is.odysseus.rest2.client.api.Pair;

public interface Authentication {
	/**
	 * Apply authentication settings to header and query params.
	 *
	 * @param queryParams  List of query parameters
	 * @param headerParams Map of header parameters
	 */
	void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
