/* Generated By:JJTree: Do not edit this line. ASTGroupOrUnionGraphPattern.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniol.inf.is.odysseus.sparql.parser.ast;

public
class ASTGroupOrUnionGraphPattern extends SimpleNode {
  public ASTGroupOrUnionGraphPattern(int id) {
    super(id);
  }

  public ASTGroupOrUnionGraphPattern(SPARQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SPARQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a4b27a54a054c29a5baed8a59e940b0b (do not edit this line) */
