/*******************************************************************************
 * Copyright 2012 The Odysseus Team
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
/* Generated By:JJTree&JavaCC: Do not edit this line. SPARQLParserConstants.java */
/*
 * (c) Copyright 2004, 2005, 2006, 2007 Hewlett-Packard Development Company, LP
 * All rights reserved.
 */

package de.uniol.inf.is.odysseus.sparql.parser.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface SPARQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS = 6;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int IRIref = 8;
  /** RegularExpression Id. */
  int PNAME_NS = 9;
  /** RegularExpression Id. */
  int PNAME_LN = 10;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 11;
  /** RegularExpression Id. */
  int VAR1 = 12;
  /** RegularExpression Id. */
  int VAR2 = 13;
  /** RegularExpression Id. */
  int LANGTAG = 14;
  /** RegularExpression Id. */
  int A2Z = 15;
  /** RegularExpression Id. */
  int A2ZN = 16;
  /** RegularExpression Id. */
  int KW_A = 17;
  /** RegularExpression Id. */
  int BASE = 18;
  /** RegularExpression Id. */
  int PREFIX = 19;
  /** RegularExpression Id. */
  int SELECT = 20;
  /** RegularExpression Id. */
  int INTO = 21;
  /** RegularExpression Id. */
  int FILE = 22;
  /** RegularExpression Id. */
  int DISTINCT = 23;
  /** RegularExpression Id. */
  int REDUCED = 24;
  /** RegularExpression Id. */
  int DESCRIBE = 25;
  /** RegularExpression Id. */
  int CONSTRUCT = 26;
  /** RegularExpression Id. */
  int ASK = 27;
  /** RegularExpression Id. */
  int LIMIT = 28;
  /** RegularExpression Id. */
  int OFFSET = 29;
  /** RegularExpression Id. */
  int ORDER = 30;
  /** RegularExpression Id. */
  int BY = 31;
  /** RegularExpression Id. */
  int GROUP = 32;
  /** RegularExpression Id. */
  int ASC = 33;
  /** RegularExpression Id. */
  int DESC = 34;
  /** RegularExpression Id. */
  int AVG = 35;
  /** RegularExpression Id. */
  int MAX = 36;
  /** RegularExpression Id. */
  int MIN = 37;
  /** RegularExpression Id. */
  int SUM = 38;
  /** RegularExpression Id. */
  int COUNT = 39;
  /** RegularExpression Id. */
  int NAMED = 40;
  /** RegularExpression Id. */
  int FROM = 41;
  /** RegularExpression Id. */
  int STREAM = 42;
  /** RegularExpression Id. */
  int PERSISTENT = 43;
  /** RegularExpression Id. */
  int CREATE = 44;
  /** RegularExpression Id. */
  int ATTACH = 45;
  /** RegularExpression Id. */
  int ADD = 46;
  /** RegularExpression Id. */
  int WITH = 47;
  /** RegularExpression Id. */
  int CSV = 48;
  /** RegularExpression Id. */
  int CHANNEL = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;
  /** RegularExpression Id. */
  int IPADDRESS = 51;
  /** RegularExpression Id. */
  int SOCKET = 52;
  /** RegularExpression Id. */
  int WINDOW = 53;
  /** RegularExpression Id. */
  int RANGE = 54;
  /** RegularExpression Id. */
  int SLIDE = 55;
  /** RegularExpression Id. */
  int ADVANCE = 56;
  /** RegularExpression Id. */
  int FIXED = 57;
  /** RegularExpression Id. */
  int ELEMS = 58;
  /** RegularExpression Id. */
  int PWINDOW = 59;
  /** RegularExpression Id. */
  int START = 60;
  /** RegularExpression Id. */
  int END = 61;
  /** RegularExpression Id. */
  int MS = 62;
  /** RegularExpression Id. */
  int S = 63;
  /** RegularExpression Id. */
  int MINUTE = 64;
  /** RegularExpression Id. */
  int HOUR = 65;
  /** RegularExpression Id. */
  int DAY = 66;
  /** RegularExpression Id. */
  int WEEK = 67;
  /** RegularExpression Id. */
  int MONTH = 68;
  /** RegularExpression Id. */
  int YEAR = 69;
  /** RegularExpression Id. */
  int WHERE = 70;
  /** RegularExpression Id. */
  int AND = 71;
  /** RegularExpression Id. */
  int GRAPH = 72;
  /** RegularExpression Id. */
  int OPTIONAL = 73;
  /** RegularExpression Id. */
  int UNION = 74;
  /** RegularExpression Id. */
  int FILTER = 75;
  /** RegularExpression Id. */
  int BOUND = 76;
  /** RegularExpression Id. */
  int STR = 77;
  /** RegularExpression Id. */
  int DTYPE = 78;
  /** RegularExpression Id. */
  int LANG = 79;
  /** RegularExpression Id. */
  int LANGMATCHES = 80;
  /** RegularExpression Id. */
  int IS_URI = 81;
  /** RegularExpression Id. */
  int IS_IRI = 82;
  /** RegularExpression Id. */
  int IS_BLANK = 83;
  /** RegularExpression Id. */
  int IS_LITERAL = 84;
  /** RegularExpression Id. */
  int REGEX = 85;
  /** RegularExpression Id. */
  int SAME_TERM = 86;
  /** RegularExpression Id. */
  int TRUE = 87;
  /** RegularExpression Id. */
  int FALSE = 88;
  /** RegularExpression Id. */
  int DIGITS = 89;
  /** RegularExpression Id. */
  int INTEGER = 90;
  /** RegularExpression Id. */
  int DECIMAL = 91;
  /** RegularExpression Id. */
  int DOUBLE = 92;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 93;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 94;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 95;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 96;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 97;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 98;
  /** RegularExpression Id. */
  int EXPONENT = 99;
  /** RegularExpression Id. */
  int QUOTE_3D = 100;
  /** RegularExpression Id. */
  int QUOTE_3S = 101;
  /** RegularExpression Id. */
  int ECHAR = 102;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 103;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 104;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 105;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 106;
  /** RegularExpression Id. */
  int IDENTIFIER = 107;
  /** RegularExpression Id. */
  int LETTER = 108;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 109;
  /** RegularExpression Id. */
  int LPAREN = 110;
  /** RegularExpression Id. */
  int RPAREN = 111;
  /** RegularExpression Id. */
  int NIL = 112;
  /** RegularExpression Id. */
  int LBRACE = 113;
  /** RegularExpression Id. */
  int RBRACE = 114;
  /** RegularExpression Id. */
  int LBRACKET = 115;
  /** RegularExpression Id. */
  int RBRACKET = 116;
  /** RegularExpression Id. */
  int ANON = 117;
  /** RegularExpression Id. */
  int SEMICOLON = 118;
  /** RegularExpression Id. */
  int COMMA = 119;
  /** RegularExpression Id. */
  int DOT = 120;
  /** RegularExpression Id. */
  int EQ = 121;
  /** RegularExpression Id. */
  int NE = 122;
  /** RegularExpression Id. */
  int GT = 123;
  /** RegularExpression Id. */
  int LT = 124;
  /** RegularExpression Id. */
  int LE = 125;
  /** RegularExpression Id. */
  int GE = 126;
  /** RegularExpression Id. */
  int BANG = 127;
  /** RegularExpression Id. */
  int TILDE = 128;
  /** RegularExpression Id. */
  int SC_OR = 129;
  /** RegularExpression Id. */
  int SC_AND = 130;
  /** RegularExpression Id. */
  int PLUS = 131;
  /** RegularExpression Id. */
  int MINUS = 132;
  /** RegularExpression Id. */
  int STAR = 133;
  /** RegularExpression Id. */
  int SLASH = 134;
  /** RegularExpression Id. */
  int DATATYPE = 135;
  /** RegularExpression Id. */
  int AT = 136;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 137;
  /** RegularExpression Id. */
  int PN_CHARS_U = 138;
  /** RegularExpression Id. */
  int PN_CHARS = 139;
  /** RegularExpression Id. */
  int PN_PREFIX = 140;
  /** RegularExpression Id. */
  int PN_LOCAL = 141;
  /** RegularExpression Id. */
  int VARNAME = 142;
  /** RegularExpression Id. */
  int UNKNOWN = 143;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<WS>",
    "<SINGLE_LINE_COMMENT>",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"select\"",
    "\"into\"",
    "\"file\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"group\"",
    "\"asc\"",
    "\"desc\"",
    "\"avg\"",
    "\"max\"",
    "\"min\"",
    "\"sum\"",
    "\"count\"",
    "\"named\"",
    "\"from\"",
    "\"stream\"",
    "\"persistent\"",
    "\"create\"",
    "\"attach\"",
    "\"add\"",
    "\"with\"",
    "\"csv\"",
    "\"channel\"",
    "<DIGIT>",
    "<IPADDRESS>",
    "\"socket\"",
    "\"window\"",
    "\"range\"",
    "\"slide\"",
    "\"advance\"",
    "\"fixed\"",
    "\"elems\"",
    "\"pwindow\"",
    "\"start\"",
    "\"end\"",
    "\"MS\"",
    "\"S\"",
    "\"minute\"",
    "\"hour\"",
    "\"day\"",
    "\"week\"",
    "\"month\"",
    "\"year\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"filter\"",
    "\"bound\"",
    "\"str\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"true\"",
    "\"false\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"~\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<UNKNOWN>",
  };

}
