/*
* generated by Xtext
*/
package de.uniol.inf.is.odysseus.iql.qdl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import de.uniol.inf.is.odysseus.iql.basic.services.BasicIQLGrammarAccess;

@Singleton
public class QDLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class QDLModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QDLModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQDLModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNamespacesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNamespacesIQLNamespaceParserRuleCall_1_0 = (RuleCall)cNamespacesAssignment_1.eContents().get(0);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsQDLTypeDefinitionParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		
		//QDLModel returns iql::IQLModel:
		//	{QDLModel} namespaces+=IQLNamespace* elements+=QDLTypeDefinition*;
		public ParserRule getRule() { return rule; }

		//{QDLModel} namespaces+=IQLNamespace* elements+=QDLTypeDefinition*
		public Group getGroup() { return cGroup; }

		//{QDLModel}
		public Action getQDLModelAction_0() { return cQDLModelAction_0; }

		//namespaces+=IQLNamespace*
		public Assignment getNamespacesAssignment_1() { return cNamespacesAssignment_1; }

		//IQLNamespace
		public RuleCall getNamespacesIQLNamespaceParserRuleCall_1_0() { return cNamespacesIQLNamespaceParserRuleCall_1_0; }

		//elements+=QDLTypeDefinition*
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }

		//QDLTypeDefinition
		public RuleCall getElementsQDLTypeDefinitionParserRuleCall_2_0() { return cElementsQDLTypeDefinitionParserRuleCall_2_0; }
	}

	public class QDLTypeDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QDLTypeDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQDLTypeDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cJavametadataAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cJavametadataIQLJavaMetadataParserRuleCall_1_0 = (RuleCall)cJavametadataAssignment_1.eContents().get(0);
		private final Assignment cInnerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cInnerAlternatives_2_0 = (Alternatives)cInnerAssignment_2.eContents().get(0);
		private final RuleCall cInnerIQLClassParserRuleCall_2_0_0 = (RuleCall)cInnerAlternatives_2_0.eContents().get(0);
		private final RuleCall cInnerIQLInterfaceParserRuleCall_2_0_1 = (RuleCall)cInnerAlternatives_2_0.eContents().get(1);
		private final RuleCall cInnerQDLQueryParserRuleCall_2_0_2 = (RuleCall)cInnerAlternatives_2_0.eContents().get(2);
		
		//QDLTypeDefinition returns iql::IQLTypeDefinition:
		//	{QDLTypeDefinition} javametadata+=IQLJavaMetadata* inner=(IQLClass | IQLInterface | QDLQuery);
		public ParserRule getRule() { return rule; }

		//{QDLTypeDefinition} javametadata+=IQLJavaMetadata* inner=(IQLClass | IQLInterface | QDLQuery)
		public Group getGroup() { return cGroup; }

		//{QDLTypeDefinition}
		public Action getQDLTypeDefinitionAction_0() { return cQDLTypeDefinitionAction_0; }

		//javametadata+=IQLJavaMetadata*
		public Assignment getJavametadataAssignment_1() { return cJavametadataAssignment_1; }

		//IQLJavaMetadata
		public RuleCall getJavametadataIQLJavaMetadataParserRuleCall_1_0() { return cJavametadataIQLJavaMetadataParserRuleCall_1_0; }

		//inner=(IQLClass | IQLInterface | QDLQuery)
		public Assignment getInnerAssignment_2() { return cInnerAssignment_2; }

		//IQLClass | IQLInterface | QDLQuery
		public Alternatives getInnerAlternatives_2_0() { return cInnerAlternatives_2_0; }

		//IQLClass
		public RuleCall getInnerIQLClassParserRuleCall_2_0_0() { return cInnerIQLClassParserRuleCall_2_0_0; }

		//IQLInterface
		public RuleCall getInnerIQLInterfaceParserRuleCall_2_0_1() { return cInnerIQLInterfaceParserRuleCall_2_0_1; }

		//QDLQuery
		public RuleCall getInnerQDLQueryParserRuleCall_2_0_2() { return cInnerQDLQueryParserRuleCall_2_0_2; }
	}

	public class QDLQueryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QDLQuery");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQDLQueryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cQueryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSimpleNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSimpleNameIDTerminalRuleCall_2_0 = (RuleCall)cSimpleNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cMetadataListAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cMetadataListIQLMetadataListParserRuleCall_3_1_0 = (RuleCall)cMetadataListAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cStatementsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStatementsIQLStatementBlockParserRuleCall_4_0 = (RuleCall)cStatementsAssignment_4.eContents().get(0);
		
		//QDLQuery returns types::JvmGenericType:
		//	{QDLQuery} "query" simpleName=ID ("(" metadataList=IQLMetadataList? ")")? statements=IQLStatementBlock;
		public ParserRule getRule() { return rule; }

		//{QDLQuery} "query" simpleName=ID ("(" metadataList=IQLMetadataList? ")")? statements=IQLStatementBlock
		public Group getGroup() { return cGroup; }

		//{QDLQuery}
		public Action getQDLQueryAction_0() { return cQDLQueryAction_0; }

		//"query"
		public Keyword getQueryKeyword_1() { return cQueryKeyword_1; }

		//simpleName=ID
		public Assignment getSimpleNameAssignment_2() { return cSimpleNameAssignment_2; }

		//ID
		public RuleCall getSimpleNameIDTerminalRuleCall_2_0() { return cSimpleNameIDTerminalRuleCall_2_0; }

		//("(" metadataList=IQLMetadataList? ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }

		//metadataList=IQLMetadataList?
		public Assignment getMetadataListAssignment_3_1() { return cMetadataListAssignment_3_1; }

		//IQLMetadataList
		public RuleCall getMetadataListIQLMetadataListParserRuleCall_3_1_0() { return cMetadataListIQLMetadataListParserRuleCall_3_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }

		//statements=IQLStatementBlock
		public Assignment getStatementsAssignment_4() { return cStatementsAssignment_4; }

		//IQLStatementBlock
		public RuleCall getStatementsIQLStatementBlockParserRuleCall_4_0() { return cStatementsIQLStatementBlockParserRuleCall_4_0; }
	}

	public class IQLAssignmentExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IQLAssignmentExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIQLSubscribeExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cGroup_1_0.eContents().get(0);
		private final Action cIQLAssignmentExpressionLeftOperandAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Assignment cOpAssignment_1_0_0_1 = (Assignment)cGroup_1_0_0.eContents().get(1);
		private final RuleCall cOpOpAssignParserRuleCall_1_0_0_1_0 = (RuleCall)cOpAssignment_1_0_0_1.eContents().get(0);
		private final Assignment cRightOperandAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightOperandIQLAssignmentExpressionParserRuleCall_1_1_0 = (RuleCall)cRightOperandAssignment_1_1.eContents().get(0);
		
		//IQLAssignmentExpression returns iql::IQLExpression:
		//	IQLSubscribeExpression (=> ({iql::IQLAssignmentExpression.leftOperand=current} op=OpAssign)
		//	rightOperand=IQLAssignmentExpression)?;
		public ParserRule getRule() { return rule; }

		//IQLSubscribeExpression (=> ({iql::IQLAssignmentExpression.leftOperand=current} op=OpAssign)
		//rightOperand=IQLAssignmentExpression)?
		public Group getGroup() { return cGroup; }

		//IQLSubscribeExpression
		public RuleCall getIQLSubscribeExpressionParserRuleCall_0() { return cIQLSubscribeExpressionParserRuleCall_0; }

		//(=> ({iql::IQLAssignmentExpression.leftOperand=current} op=OpAssign) rightOperand=IQLAssignmentExpression)?
		public Group getGroup_1() { return cGroup_1; }

		//=> ({iql::IQLAssignmentExpression.leftOperand=current} op=OpAssign)
		public Group getGroup_1_0() { return cGroup_1_0; }

		//{iql::IQLAssignmentExpression.leftOperand=current} op=OpAssign
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }

		//{iql::IQLAssignmentExpression.leftOperand=current}
		public Action getIQLAssignmentExpressionLeftOperandAction_1_0_0_0() { return cIQLAssignmentExpressionLeftOperandAction_1_0_0_0; }

		//op=OpAssign
		public Assignment getOpAssignment_1_0_0_1() { return cOpAssignment_1_0_0_1; }

		//OpAssign
		public RuleCall getOpOpAssignParserRuleCall_1_0_0_1_0() { return cOpOpAssignParserRuleCall_1_0_0_1_0; }

		//rightOperand=IQLAssignmentExpression
		public Assignment getRightOperandAssignment_1_1() { return cRightOperandAssignment_1_1; }

		//IQLAssignmentExpression
		public RuleCall getRightOperandIQLAssignmentExpressionParserRuleCall_1_1_0() { return cRightOperandIQLAssignmentExpressionParserRuleCall_1_1_0; }
	}

	public class IQLSubscribeExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IQLSubscribeExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIQLPortExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cGroup_1_0.eContents().get(0);
		private final Action cIQLSubscribeExpressionLeftOperandAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Assignment cOpAssignment_1_0_0_1 = (Assignment)cGroup_1_0_0.eContents().get(1);
		private final RuleCall cOpIQLSubscribeParserRuleCall_1_0_0_1_0 = (RuleCall)cOpAssignment_1_0_0_1.eContents().get(0);
		private final Assignment cRightOperandAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightOperandIQLPortExpressionParserRuleCall_1_1_0 = (RuleCall)cRightOperandAssignment_1_1.eContents().get(0);
		
		//IQLSubscribeExpression returns iql::IQLExpression:
		//	IQLPortExpression (=> ({IQLSubscribeExpression.leftOperand=current} op=IQLSubscribe)
		//	rightOperand=IQLPortExpression)*;
		public ParserRule getRule() { return rule; }

		//IQLPortExpression (=> ({IQLSubscribeExpression.leftOperand=current} op=IQLSubscribe) rightOperand=IQLPortExpression)*
		public Group getGroup() { return cGroup; }

		//IQLPortExpression
		public RuleCall getIQLPortExpressionParserRuleCall_0() { return cIQLPortExpressionParserRuleCall_0; }

		//(=> ({IQLSubscribeExpression.leftOperand=current} op=IQLSubscribe) rightOperand=IQLPortExpression)*
		public Group getGroup_1() { return cGroup_1; }

		//=> ({IQLSubscribeExpression.leftOperand=current} op=IQLSubscribe)
		public Group getGroup_1_0() { return cGroup_1_0; }

		//{IQLSubscribeExpression.leftOperand=current} op=IQLSubscribe
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }

		//{IQLSubscribeExpression.leftOperand=current}
		public Action getIQLSubscribeExpressionLeftOperandAction_1_0_0_0() { return cIQLSubscribeExpressionLeftOperandAction_1_0_0_0; }

		//op=IQLSubscribe
		public Assignment getOpAssignment_1_0_0_1() { return cOpAssignment_1_0_0_1; }

		//IQLSubscribe
		public RuleCall getOpIQLSubscribeParserRuleCall_1_0_0_1_0() { return cOpIQLSubscribeParserRuleCall_1_0_0_1_0; }

		//rightOperand=IQLPortExpression
		public Assignment getRightOperandAssignment_1_1() { return cRightOperandAssignment_1_1; }

		//IQLPortExpression
		public RuleCall getRightOperandIQLPortExpressionParserRuleCall_1_1_0() { return cRightOperandIQLPortExpressionParserRuleCall_1_1_0; }
	}

	public class IQLPortExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IQLPortExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIQLLogicalOrExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cGroup_1.eContents().get(0);
		private final Group cGroup_1_0_0 = (Group)cGroup_1_0.eContents().get(0);
		private final Action cIQLPortExpressionLeftOperandAction_1_0_0_0 = (Action)cGroup_1_0_0.eContents().get(0);
		private final Assignment cOpAssignment_1_0_0_1 = (Assignment)cGroup_1_0_0.eContents().get(1);
		private final Keyword cOpColonKeyword_1_0_0_1_0 = (Keyword)cOpAssignment_1_0_0_1.eContents().get(0);
		private final Assignment cRightOperandAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightOperandIQLLogicalOrExpressionParserRuleCall_1_1_0 = (RuleCall)cRightOperandAssignment_1_1.eContents().get(0);
		
		//IQLPortExpression returns iql::IQLExpression:
		//	IQLLogicalOrExpression (=> ({IQLPortExpression.leftOperand=current} op=":") rightOperand=IQLLogicalOrExpression)*;
		public ParserRule getRule() { return rule; }

		//IQLLogicalOrExpression (=> ({IQLPortExpression.leftOperand=current} op=":") rightOperand=IQLLogicalOrExpression)*
		public Group getGroup() { return cGroup; }

		//IQLLogicalOrExpression
		public RuleCall getIQLLogicalOrExpressionParserRuleCall_0() { return cIQLLogicalOrExpressionParserRuleCall_0; }

		//(=> ({IQLPortExpression.leftOperand=current} op=":") rightOperand=IQLLogicalOrExpression)*
		public Group getGroup_1() { return cGroup_1; }

		//=> ({IQLPortExpression.leftOperand=current} op=":")
		public Group getGroup_1_0() { return cGroup_1_0; }

		//{IQLPortExpression.leftOperand=current} op=":"
		public Group getGroup_1_0_0() { return cGroup_1_0_0; }

		//{IQLPortExpression.leftOperand=current}
		public Action getIQLPortExpressionLeftOperandAction_1_0_0_0() { return cIQLPortExpressionLeftOperandAction_1_0_0_0; }

		//op=":"
		public Assignment getOpAssignment_1_0_0_1() { return cOpAssignment_1_0_0_1; }

		//":"
		public Keyword getOpColonKeyword_1_0_0_1_0() { return cOpColonKeyword_1_0_0_1_0; }

		//rightOperand=IQLLogicalOrExpression
		public Assignment getRightOperandAssignment_1_1() { return cRightOperandAssignment_1_1; }

		//IQLLogicalOrExpression
		public RuleCall getRightOperandIQLLogicalOrExpressionParserRuleCall_1_1_0() { return cRightOperandIQLLogicalOrExpressionParserRuleCall_1_1_0; }
	}

	public class IQLSubscribeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IQLSubscribe");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLessThanSignHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//IQLSubscribe:
		//	"->" | "<-";
		public ParserRule getRule() { return rule; }

		//"->" | "<-"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_0() { return cHyphenMinusGreaterThanSignKeyword_0; }

		//"<-"
		public Keyword getLessThanSignHyphenMinusKeyword_1() { return cLessThanSignHyphenMinusKeyword_1; }
	}

	public class IQLMetadataValueSingleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IQLMetadataValueSingle");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cIQLMetadataValueSingleIntAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cIQLMetadataValueSingleDoubleAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueDOUBLETerminalRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cIQLMetadataValueSingleStringAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cValueAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cValueAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cIQLMetadataValueSingleBooleanAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueBOOLEANTerminalRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cGroup_4.eContents().get(0);
		private final Action cQDLMetadataValueSingleIDAction_4_0_0 = (Action)cGroup_4_0.eContents().get(0);
		private final Assignment cValueAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_4_0_1_0 = (RuleCall)cValueAssignment_4_0_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cIQLMetadataValueSingleTypeRefAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueJvmTypeReferenceParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Action cIQLMetadataValueSingleNullAction_6_0 = (Action)cGroup_6.eContents().get(0);
		private final Assignment cValueAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final Keyword cValueNullKeyword_6_1_0 = (Keyword)cValueAssignment_6_1.eContents().get(0);
		
		//IQLMetadataValueSingle returns iql::IQLMetadataValue:
		//	{IQLMetadataValueSingleInt} value=INT | {IQLMetadataValueSingleDouble} value=DOUBLE | {IQLMetadataValueSingleString}
		//	value=STRING | {IQLMetadataValueSingleBoolean} value=BOOLEAN | => ({QDLMetadataValueSingleID} value=ID) |
		//	{IQLMetadataValueSingleTypeRef} value=JvmTypeReference | {IQLMetadataValueSingleNull} value="null";
		public ParserRule getRule() { return rule; }

		//{IQLMetadataValueSingleInt} value=INT | {IQLMetadataValueSingleDouble} value=DOUBLE | {IQLMetadataValueSingleString}
		//value=STRING | {IQLMetadataValueSingleBoolean} value=BOOLEAN | => ({QDLMetadataValueSingleID} value=ID) |
		//{IQLMetadataValueSingleTypeRef} value=JvmTypeReference | {IQLMetadataValueSingleNull} value="null"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{IQLMetadataValueSingleInt} value=INT
		public Group getGroup_0() { return cGroup_0; }

		//{IQLMetadataValueSingleInt}
		public Action getIQLMetadataValueSingleIntAction_0_0() { return cIQLMetadataValueSingleIntAction_0_0; }

		//value=INT
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_0_1_0() { return cValueINTTerminalRuleCall_0_1_0; }

		//{IQLMetadataValueSingleDouble} value=DOUBLE
		public Group getGroup_1() { return cGroup_1; }

		//{IQLMetadataValueSingleDouble}
		public Action getIQLMetadataValueSingleDoubleAction_1_0() { return cIQLMetadataValueSingleDoubleAction_1_0; }

		//value=DOUBLE
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }

		//DOUBLE
		public RuleCall getValueDOUBLETerminalRuleCall_1_1_0() { return cValueDOUBLETerminalRuleCall_1_1_0; }

		//{IQLMetadataValueSingleString} value=STRING
		public Group getGroup_2() { return cGroup_2; }

		//{IQLMetadataValueSingleString}
		public Action getIQLMetadataValueSingleStringAction_2_0() { return cIQLMetadataValueSingleStringAction_2_0; }

		//value=STRING
		public Assignment getValueAssignment_2_1() { return cValueAssignment_2_1; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_1_0() { return cValueSTRINGTerminalRuleCall_2_1_0; }

		//{IQLMetadataValueSingleBoolean} value=BOOLEAN
		public Group getGroup_3() { return cGroup_3; }

		//{IQLMetadataValueSingleBoolean}
		public Action getIQLMetadataValueSingleBooleanAction_3_0() { return cIQLMetadataValueSingleBooleanAction_3_0; }

		//value=BOOLEAN
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }

		//BOOLEAN
		public RuleCall getValueBOOLEANTerminalRuleCall_3_1_0() { return cValueBOOLEANTerminalRuleCall_3_1_0; }

		//=> ({QDLMetadataValueSingleID} value=ID)
		public Group getGroup_4() { return cGroup_4; }

		//{QDLMetadataValueSingleID} value=ID
		public Group getGroup_4_0() { return cGroup_4_0; }

		//{QDLMetadataValueSingleID}
		public Action getQDLMetadataValueSingleIDAction_4_0_0() { return cQDLMetadataValueSingleIDAction_4_0_0; }

		//value=ID
		public Assignment getValueAssignment_4_0_1() { return cValueAssignment_4_0_1; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_4_0_1_0() { return cValueIDTerminalRuleCall_4_0_1_0; }

		//{IQLMetadataValueSingleTypeRef} value=JvmTypeReference
		public Group getGroup_5() { return cGroup_5; }

		//{IQLMetadataValueSingleTypeRef}
		public Action getIQLMetadataValueSingleTypeRefAction_5_0() { return cIQLMetadataValueSingleTypeRefAction_5_0; }

		//value=JvmTypeReference
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }

		//JvmTypeReference
		public RuleCall getValueJvmTypeReferenceParserRuleCall_5_1_0() { return cValueJvmTypeReferenceParserRuleCall_5_1_0; }

		//{IQLMetadataValueSingleNull} value="null"
		public Group getGroup_6() { return cGroup_6; }

		//{IQLMetadataValueSingleNull}
		public Action getIQLMetadataValueSingleNullAction_6_0() { return cIQLMetadataValueSingleNullAction_6_0; }

		//value="null"
		public Assignment getValueAssignment_6_1() { return cValueAssignment_6_1; }

		//"null"
		public Keyword getValueNullKeyword_6_1_0() { return cValueNullKeyword_6_1_0; }
	}
	
	
	private final QDLModelElements pQDLModel;
	private final QDLTypeDefinitionElements pQDLTypeDefinition;
	private final QDLQueryElements pQDLQuery;
	private final IQLAssignmentExpressionElements pIQLAssignmentExpression;
	private final IQLSubscribeExpressionElements pIQLSubscribeExpression;
	private final IQLPortExpressionElements pIQLPortExpression;
	private final IQLSubscribeElements pIQLSubscribe;
	private final IQLMetadataValueSingleElements pIQLMetadataValueSingle;
	
	private final Grammar grammar;

	private final BasicIQLGrammarAccess gaBasicIQL;

	@Inject
	public QDLGrammarAccess(GrammarProvider grammarProvider,
		BasicIQLGrammarAccess gaBasicIQL) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaBasicIQL = gaBasicIQL;
		this.pQDLModel = new QDLModelElements();
		this.pQDLTypeDefinition = new QDLTypeDefinitionElements();
		this.pQDLQuery = new QDLQueryElements();
		this.pIQLAssignmentExpression = new IQLAssignmentExpressionElements();
		this.pIQLSubscribeExpression = new IQLSubscribeExpressionElements();
		this.pIQLPortExpression = new IQLPortExpressionElements();
		this.pIQLSubscribe = new IQLSubscribeElements();
		this.pIQLMetadataValueSingle = new IQLMetadataValueSingleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.uniol.inf.is.odysseus.iql.qdl.QDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public BasicIQLGrammarAccess getBasicIQLGrammarAccess() {
		return gaBasicIQL;
	}

	
	//QDLModel returns iql::IQLModel:
	//	{QDLModel} namespaces+=IQLNamespace* elements+=QDLTypeDefinition*;
	public QDLModelElements getQDLModelAccess() {
		return pQDLModel;
	}
	
	public ParserRule getQDLModelRule() {
		return getQDLModelAccess().getRule();
	}

	//QDLTypeDefinition returns iql::IQLTypeDefinition:
	//	{QDLTypeDefinition} javametadata+=IQLJavaMetadata* inner=(IQLClass | IQLInterface | QDLQuery);
	public QDLTypeDefinitionElements getQDLTypeDefinitionAccess() {
		return pQDLTypeDefinition;
	}
	
	public ParserRule getQDLTypeDefinitionRule() {
		return getQDLTypeDefinitionAccess().getRule();
	}

	//QDLQuery returns types::JvmGenericType:
	//	{QDLQuery} "query" simpleName=ID ("(" metadataList=IQLMetadataList? ")")? statements=IQLStatementBlock;
	public QDLQueryElements getQDLQueryAccess() {
		return pQDLQuery;
	}
	
	public ParserRule getQDLQueryRule() {
		return getQDLQueryAccess().getRule();
	}

	//IQLAssignmentExpression returns iql::IQLExpression:
	//	IQLSubscribeExpression (=> ({iql::IQLAssignmentExpression.leftOperand=current} op=OpAssign)
	//	rightOperand=IQLAssignmentExpression)?;
	public IQLAssignmentExpressionElements getIQLAssignmentExpressionAccess() {
		return pIQLAssignmentExpression;
	}
	
	public ParserRule getIQLAssignmentExpressionRule() {
		return getIQLAssignmentExpressionAccess().getRule();
	}

	//IQLSubscribeExpression returns iql::IQLExpression:
	//	IQLPortExpression (=> ({IQLSubscribeExpression.leftOperand=current} op=IQLSubscribe)
	//	rightOperand=IQLPortExpression)*;
	public IQLSubscribeExpressionElements getIQLSubscribeExpressionAccess() {
		return pIQLSubscribeExpression;
	}
	
	public ParserRule getIQLSubscribeExpressionRule() {
		return getIQLSubscribeExpressionAccess().getRule();
	}

	//IQLPortExpression returns iql::IQLExpression:
	//	IQLLogicalOrExpression (=> ({IQLPortExpression.leftOperand=current} op=":") rightOperand=IQLLogicalOrExpression)*;
	public IQLPortExpressionElements getIQLPortExpressionAccess() {
		return pIQLPortExpression;
	}
	
	public ParserRule getIQLPortExpressionRule() {
		return getIQLPortExpressionAccess().getRule();
	}

	//IQLSubscribe:
	//	"->" | "<-";
	public IQLSubscribeElements getIQLSubscribeAccess() {
		return pIQLSubscribe;
	}
	
	public ParserRule getIQLSubscribeRule() {
		return getIQLSubscribeAccess().getRule();
	}

	//IQLMetadataValueSingle returns iql::IQLMetadataValue:
	//	{IQLMetadataValueSingleInt} value=INT | {IQLMetadataValueSingleDouble} value=DOUBLE | {IQLMetadataValueSingleString}
	//	value=STRING | {IQLMetadataValueSingleBoolean} value=BOOLEAN | => ({QDLMetadataValueSingleID} value=ID) |
	//	{IQLMetadataValueSingleTypeRef} value=JvmTypeReference | {IQLMetadataValueSingleNull} value="null";
	public IQLMetadataValueSingleElements getIQLMetadataValueSingleAccess() {
		return pIQLMetadataValueSingle;
	}
	
	public ParserRule getIQLMetadataValueSingleRule() {
		return getIQLMetadataValueSingleAccess().getRule();
	}

	//IQLModel:
	//	("namespace" name=QualifiedName ";")? namespaces+=IQLNamespace* elements+=IQLTypeDefinition*;
	public BasicIQLGrammarAccess.IQLModelElements getIQLModelAccess() {
		return gaBasicIQL.getIQLModelAccess();
	}
	
	public ParserRule getIQLModelRule() {
		return getIQLModelAccess().getRule();
	}

	//IQLTypeDefinition:
	//	{IQLTypeDefinition} javametadata+=IQLJavaMetadata* inner=(IQLClass | IQLInterface);
	public BasicIQLGrammarAccess.IQLTypeDefinitionElements getIQLTypeDefinitionAccess() {
		return gaBasicIQL.getIQLTypeDefinitionAccess();
	}
	
	public ParserRule getIQLTypeDefinitionRule() {
		return getIQLTypeDefinitionAccess().getRule();
	}

	//IQLNamespace:
	//	"use" importedNamespace=QualifiedNameWithWildcard ";";
	public BasicIQLGrammarAccess.IQLNamespaceElements getIQLNamespaceAccess() {
		return gaBasicIQL.getIQLNamespaceAccess();
	}
	
	public ParserRule getIQLNamespaceRule() {
		return getIQLNamespaceAccess().getRule();
	}

	//IQLClass returns types::JvmGenericType:
	//	{IQLClass} "class" simpleName=ID ("extends" extendedClass=JvmTypeReference)? ("implements"
	//	extendedInterfaces+=JvmTypeReference ("," extendedInterfaces+=JvmTypeReference)?)? "{" members+=(IQLAttribute |
	//	IQLMethod | IQLJavaMember)* "}";
	public BasicIQLGrammarAccess.IQLClassElements getIQLClassAccess() {
		return gaBasicIQL.getIQLClassAccess();
	}
	
	public ParserRule getIQLClassRule() {
		return getIQLClassAccess().getRule();
	}

	//IQLInterface returns types::JvmGenericType:
	//	{IQLInterface} "interface" simpleName=ID ("extends" extendedInterfaces+=JvmTypeReference (","
	//	extendedInterfaces+=JvmTypeReference)?)? "{" members+=(IQLMethodDeclarationMember | IQLJavaMember)* "}";
	public BasicIQLGrammarAccess.IQLInterfaceElements getIQLInterfaceAccess() {
		return gaBasicIQL.getIQLInterfaceAccess();
	}
	
	public ParserRule getIQLInterfaceRule() {
		return getIQLInterfaceAccess().getRule();
	}

	//IQLJavaMetadata:
	//	{IQLJavaMetadata} "$*" text=IQLJava "*$";
	public BasicIQLGrammarAccess.IQLJavaMetadataElements getIQLJavaMetadataAccess() {
		return gaBasicIQL.getIQLJavaMetadataAccess();
	}
	
	public ParserRule getIQLJavaMetadataRule() {
		return getIQLJavaMetadataAccess().getRule();
	}

	///////////////////////////////////////////////
	///////////////////////////////////////////////
	///////////////////////////////////////////////
	//IQLAttribute returns types::JvmField:
	//	{IQLAttribute} type=JvmTypeReference simpleName=ID init=IQLVariableInitialization? ";";
	public BasicIQLGrammarAccess.IQLAttributeElements getIQLAttributeAccess() {
		return gaBasicIQL.getIQLAttributeAccess();
	}
	
	public ParserRule getIQLAttributeRule() {
		return getIQLAttributeAccess().getRule();
	}

	//JvmTypeReference returns types::JvmTypeReference:
	//	IQLSimpleTypeRef | IQLArrayTypeRef;
	public BasicIQLGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaBasicIQL.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//JvmType returns types::JvmType:
	//	IQLSimpleType | IQLArrayType;
	public BasicIQLGrammarAccess.JvmTypeElements getJvmTypeAccess() {
		return gaBasicIQL.getJvmTypeAccess();
	}
	
	public ParserRule getJvmTypeRule() {
		return getJvmTypeAccess().getRule();
	}

	//IQLSimpleTypeRef:
	//	type=IQLSimpleType;
	public BasicIQLGrammarAccess.IQLSimpleTypeRefElements getIQLSimpleTypeRefAccess() {
		return gaBasicIQL.getIQLSimpleTypeRefAccess();
	}
	
	public ParserRule getIQLSimpleTypeRefRule() {
		return getIQLSimpleTypeRefAccess().getRule();
	}

	//IQLArrayTypeRef:
	//	type=IQLArrayType;
	public BasicIQLGrammarAccess.IQLArrayTypeRefElements getIQLArrayTypeRefAccess() {
		return gaBasicIQL.getIQLArrayTypeRefAccess();
	}
	
	public ParserRule getIQLArrayTypeRefRule() {
		return getIQLArrayTypeRefAccess().getRule();
	}

	//IQLSimpleType:
	//	type=[types::JvmType|QualifiedName];
	public BasicIQLGrammarAccess.IQLSimpleTypeElements getIQLSimpleTypeAccess() {
		return gaBasicIQL.getIQLSimpleTypeAccess();
	}
	
	public ParserRule getIQLSimpleTypeRule() {
		return getIQLSimpleTypeAccess().getRule();
	}

	//IQLArrayType:
	//	type=[types::JvmType|QualifiedName] dimensions+=ArrayBrackets+;
	public BasicIQLGrammarAccess.IQLArrayTypeElements getIQLArrayTypeAccess() {
		return gaBasicIQL.getIQLArrayTypeAccess();
	}
	
	public ParserRule getIQLArrayTypeRule() {
		return getIQLArrayTypeAccess().getRule();
	}

	//ArrayBrackets:
	//	"[" "]";
	public BasicIQLGrammarAccess.ArrayBracketsElements getArrayBracketsAccess() {
		return gaBasicIQL.getArrayBracketsAccess();
	}
	
	public ParserRule getArrayBracketsRule() {
		return getArrayBracketsAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//	parameterType=JvmTypeReference name=ID;
	public BasicIQLGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaBasicIQL.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//IQLMethod returns types::JvmOperation:
	//	{IQLMethod} override?="override"? simpleName=ID ("(" (parameters+=JvmFormalParameter (","
	//	parameters+=JvmFormalParameter)*)? ")")? (":" returnType=JvmTypeReference)? body=IQLStatementBlock;
	public BasicIQLGrammarAccess.IQLMethodElements getIQLMethodAccess() {
		return gaBasicIQL.getIQLMethodAccess();
	}
	
	public ParserRule getIQLMethodRule() {
		return getIQLMethodAccess().getRule();
	}

	//IQLMethodDeclarationMember returns types::JvmOperation:
	//	{IQLMethodDeclarationMember} simpleName=ID "(" (parameters+=JvmFormalParameter (","
	//	parameters+=JvmFormalParameter)*)? ")" (":" returnType=JvmTypeReference)? ";";
	public BasicIQLGrammarAccess.IQLMethodDeclarationMemberElements getIQLMethodDeclarationMemberAccess() {
		return gaBasicIQL.getIQLMethodDeclarationMemberAccess();
	}
	
	public ParserRule getIQLMethodDeclarationMemberRule() {
		return getIQLMethodDeclarationMemberAccess().getRule();
	}

	//IQLJavaMember returns types::JvmMember:
	//	{IQLJavaMember} "$*" text=IQLJava "*$";
	public BasicIQLGrammarAccess.IQLJavaMemberElements getIQLJavaMemberAccess() {
		return gaBasicIQL.getIQLJavaMemberAccess();
	}
	
	public ParserRule getIQLJavaMemberRule() {
		return getIQLJavaMemberAccess().getRule();
	}

	///////////////////////////////////////////////
	///////////////////////////////////////////////
	///////////////////////////////////////////////
	//IQLMetadataList:
	//	elements+=IQLMetadata ("," elements+=IQLMetadata)*;
	public BasicIQLGrammarAccess.IQLMetadataListElements getIQLMetadataListAccess() {
		return gaBasicIQL.getIQLMetadataListAccess();
	}
	
	public ParserRule getIQLMetadataListRule() {
		return getIQLMetadataListAccess().getRule();
	}

	//IQLMetadata:
	//	name=ID ("=" value=IQLMetadataValue)?;
	public BasicIQLGrammarAccess.IQLMetadataElements getIQLMetadataAccess() {
		return gaBasicIQL.getIQLMetadataAccess();
	}
	
	public ParserRule getIQLMetadataRule() {
		return getIQLMetadataAccess().getRule();
	}

	//IQLMetadataValue:
	//	IQLMetadataValueSingle | IQLMetadataValueList | IQLMetadataValueMap;
	public BasicIQLGrammarAccess.IQLMetadataValueElements getIQLMetadataValueAccess() {
		return gaBasicIQL.getIQLMetadataValueAccess();
	}
	
	public ParserRule getIQLMetadataValueRule() {
		return getIQLMetadataValueAccess().getRule();
	}

	//IQLMetadataValueList returns IQLMetadataValue:
	//	{IQLMetadataValueList} "[" (elements+=IQLMetadataValue ("," elements+=IQLMetadataValue)*)? "]";
	public BasicIQLGrammarAccess.IQLMetadataValueListElements getIQLMetadataValueListAccess() {
		return gaBasicIQL.getIQLMetadataValueListAccess();
	}
	
	public ParserRule getIQLMetadataValueListRule() {
		return getIQLMetadataValueListAccess().getRule();
	}

	//IQLMetadataValueMap returns IQLMetadataValue:
	//	{IQLMetadataValueMap} "{" (elements+=IQLMetadataValueMapElement ("," elements+=IQLMetadataValueMapElement)*)? "}";
	public BasicIQLGrammarAccess.IQLMetadataValueMapElements getIQLMetadataValueMapAccess() {
		return gaBasicIQL.getIQLMetadataValueMapAccess();
	}
	
	public ParserRule getIQLMetadataValueMapRule() {
		return getIQLMetadataValueMapAccess().getRule();
	}

	//IQLMetadataValueMapElement:
	//	key=IQLMetadataValue "=" value=IQLMetadataValue;
	public BasicIQLGrammarAccess.IQLMetadataValueMapElementElements getIQLMetadataValueMapElementAccess() {
		return gaBasicIQL.getIQLMetadataValueMapElementAccess();
	}
	
	public ParserRule getIQLMetadataValueMapElementRule() {
		return getIQLMetadataValueMapElementAccess().getRule();
	}

	///////////////////////////////////////////////
	///////////////////////////////////////////////
	///////////////////////////////////////////////
	//IQLVariableDeclaration returns types::JvmIdentifiableElement:
	//	{IQLVariableDeclaration} ref=JvmTypeReference name=ID;
	public BasicIQLGrammarAccess.IQLVariableDeclarationElements getIQLVariableDeclarationAccess() {
		return gaBasicIQL.getIQLVariableDeclarationAccess();
	}
	
	public ParserRule getIQLVariableDeclarationRule() {
		return getIQLVariableDeclarationAccess().getRule();
	}

	//IQLVariableInitialization:
	//	{IQLVariableInitialization} (argsList=IQLArgumentsList argsMap=IQLArgumentsMap?) | "=" value=IQLExpression;
	public BasicIQLGrammarAccess.IQLVariableInitializationElements getIQLVariableInitializationAccess() {
		return gaBasicIQL.getIQLVariableInitializationAccess();
	}
	
	public ParserRule getIQLVariableInitializationRule() {
		return getIQLVariableInitializationAccess().getRule();
	}

	//IQLArgumentsList:
	//	{IQLArgumentsList} "(" (elements+=IQLExpression ("," elements+=IQLExpression)*)? ")";
	public BasicIQLGrammarAccess.IQLArgumentsListElements getIQLArgumentsListAccess() {
		return gaBasicIQL.getIQLArgumentsListAccess();
	}
	
	public ParserRule getIQLArgumentsListRule() {
		return getIQLArgumentsListAccess().getRule();
	}

	//IQLArgumentsMap:
	//	{IQLArgumentsMap} "{" (elements+=IQLArgumentsMapKeyValue ("," elements+=IQLArgumentsMapKeyValue)*)? "}";
	public BasicIQLGrammarAccess.IQLArgumentsMapElements getIQLArgumentsMapAccess() {
		return gaBasicIQL.getIQLArgumentsMapAccess();
	}
	
	public ParserRule getIQLArgumentsMapRule() {
		return getIQLArgumentsMapAccess().getRule();
	}

	//IQLArgumentsMapKeyValue:
	//	key=ID "=" value=IQLExpression;
	public BasicIQLGrammarAccess.IQLArgumentsMapKeyValueElements getIQLArgumentsMapKeyValueAccess() {
		return gaBasicIQL.getIQLArgumentsMapKeyValueAccess();
	}
	
	public ParserRule getIQLArgumentsMapKeyValueRule() {
		return getIQLArgumentsMapKeyValueAccess().getRule();
	}

	///////////////////////////////////////////////
	///////////////////////////////////////////////
	///////////////////////////////////////////////
	//IQLStatement:
	//	IQLStatementBlock | IQLExpressionStatement | IQLIfStatement | IQLWhileStatement | IQLDoWhileStatement |
	//	IQLForStatement | IQLForEachStatement | IQLSwitchStatement | IQLVariableStatement | IQLBreakStatement |
	//	IQLContinueStatement | IQLReturnStatement | IQLConstructorCallStatement | IQLJavaStatement;
	public BasicIQLGrammarAccess.IQLStatementElements getIQLStatementAccess() {
		return gaBasicIQL.getIQLStatementAccess();
	}
	
	public ParserRule getIQLStatementRule() {
		return getIQLStatementAccess().getRule();
	}

	//IQLStatementBlock returns IQLStatement:
	//	{IQLStatementBlock} "{" statements+=IQLStatement* "}";
	public BasicIQLGrammarAccess.IQLStatementBlockElements getIQLStatementBlockAccess() {
		return gaBasicIQL.getIQLStatementBlockAccess();
	}
	
	public ParserRule getIQLStatementBlockRule() {
		return getIQLStatementBlockAccess().getRule();
	}

	//IQLJavaStatement returns IQLStatement:
	//	{IQLJavaStatement} "$*" text=IQLJava "*$";
	public BasicIQLGrammarAccess.IQLJavaStatementElements getIQLJavaStatementAccess() {
		return gaBasicIQL.getIQLJavaStatementAccess();
	}
	
	public ParserRule getIQLJavaStatementRule() {
		return getIQLJavaStatementAccess().getRule();
	}

	//IQLIfStatement returns IQLStatement:
	//	{IQLIfStatement} "if" "(" predicate=IQLExpression ")" thenBody=IQLStatement ("else" elseBody=IQLStatement)?;
	public BasicIQLGrammarAccess.IQLIfStatementElements getIQLIfStatementAccess() {
		return gaBasicIQL.getIQLIfStatementAccess();
	}
	
	public ParserRule getIQLIfStatementRule() {
		return getIQLIfStatementAccess().getRule();
	}

	//IQLWhileStatement returns IQLStatement:
	//	{IQLWhileStatement} "while" "(" predicate=IQLExpression ")" body=IQLStatement;
	public BasicIQLGrammarAccess.IQLWhileStatementElements getIQLWhileStatementAccess() {
		return gaBasicIQL.getIQLWhileStatementAccess();
	}
	
	public ParserRule getIQLWhileStatementRule() {
		return getIQLWhileStatementAccess().getRule();
	}

	//IQLDoWhileStatement returns IQLStatement:
	//	{IQLDoWhileStatement} "do" body=IQLStatement "while" "(" predicate=IQLExpression ")" ";";
	public BasicIQLGrammarAccess.IQLDoWhileStatementElements getIQLDoWhileStatementAccess() {
		return gaBasicIQL.getIQLDoWhileStatementAccess();
	}
	
	public ParserRule getIQLDoWhileStatementRule() {
		return getIQLDoWhileStatementAccess().getRule();
	}

	//IQLForStatement returns IQLStatement:
	//	{IQLForStatement} "for" "(" var=IQLVariableStatement predicate=IQLExpressionStatement updateExpr=IQLExpression ")"
	//	body=IQLStatement;
	public BasicIQLGrammarAccess.IQLForStatementElements getIQLForStatementAccess() {
		return gaBasicIQL.getIQLForStatementAccess();
	}
	
	public ParserRule getIQLForStatementRule() {
		return getIQLForStatementAccess().getRule();
	}

	//IQLForEachStatement returns IQLStatement:
	//	{IQLForEachStatement} "for" "(" var=IQLVariableDeclaration ":" forExpression=IQLExpression ")" body=IQLStatement;
	public BasicIQLGrammarAccess.IQLForEachStatementElements getIQLForEachStatementAccess() {
		return gaBasicIQL.getIQLForEachStatementAccess();
	}
	
	public ParserRule getIQLForEachStatementRule() {
		return getIQLForEachStatementAccess().getRule();
	}

	//IQLSwitchStatement returns IQLStatement:
	//	{IQLSwitchStatement} "switch" "(" expr=IQLExpression ")" "{" cases+=IQLCasePart* ("default" ":"
	//	statements+=IQLStatement*)? "}";
	public BasicIQLGrammarAccess.IQLSwitchStatementElements getIQLSwitchStatementAccess() {
		return gaBasicIQL.getIQLSwitchStatementAccess();
	}
	
	public ParserRule getIQLSwitchStatementRule() {
		return getIQLSwitchStatementAccess().getRule();
	}

	//IQLCasePart:
	//	{IQLCasePart} "case" expr=IQLLiteralExpression ":" statements+=IQLStatement*;
	public BasicIQLGrammarAccess.IQLCasePartElements getIQLCasePartAccess() {
		return gaBasicIQL.getIQLCasePartAccess();
	}
	
	public ParserRule getIQLCasePartRule() {
		return getIQLCasePartAccess().getRule();
	}

	//IQLExpressionStatement returns IQLStatement:
	//	{IQLExpressionStatement} expression=IQLExpression ";";
	public BasicIQLGrammarAccess.IQLExpressionStatementElements getIQLExpressionStatementAccess() {
		return gaBasicIQL.getIQLExpressionStatementAccess();
	}
	
	public ParserRule getIQLExpressionStatementRule() {
		return getIQLExpressionStatementAccess().getRule();
	}

	//IQLVariableStatement returns IQLStatement:
	//	{IQLVariableStatement} var=IQLVariableDeclaration init=IQLVariableInitialization ";";
	public BasicIQLGrammarAccess.IQLVariableStatementElements getIQLVariableStatementAccess() {
		return gaBasicIQL.getIQLVariableStatementAccess();
	}
	
	public ParserRule getIQLVariableStatementRule() {
		return getIQLVariableStatementAccess().getRule();
	}

	//IQLConstructorCallStatement returns IQLStatement:
	//	{IQLConstructorCallStatement} keyword=("super" | "this") args=IQLArgumentsList ";";
	public BasicIQLGrammarAccess.IQLConstructorCallStatementElements getIQLConstructorCallStatementAccess() {
		return gaBasicIQL.getIQLConstructorCallStatementAccess();
	}
	
	public ParserRule getIQLConstructorCallStatementRule() {
		return getIQLConstructorCallStatementAccess().getRule();
	}

	//IQLBreakStatement returns IQLStatement:
	//	{IQLBreakStatement} "break" ";";
	public BasicIQLGrammarAccess.IQLBreakStatementElements getIQLBreakStatementAccess() {
		return gaBasicIQL.getIQLBreakStatementAccess();
	}
	
	public ParserRule getIQLBreakStatementRule() {
		return getIQLBreakStatementAccess().getRule();
	}

	//IQLContinueStatement returns IQLStatement:
	//	{IQLContinueStatement} "continue" ";";
	public BasicIQLGrammarAccess.IQLContinueStatementElements getIQLContinueStatementAccess() {
		return gaBasicIQL.getIQLContinueStatementAccess();
	}
	
	public ParserRule getIQLContinueStatementRule() {
		return getIQLContinueStatementAccess().getRule();
	}

	//IQLReturnStatement returns IQLStatement:
	//	{IQLReturnStatement} "return" expression=IQLExpression ";";
	public BasicIQLGrammarAccess.IQLReturnStatementElements getIQLReturnStatementAccess() {
		return gaBasicIQL.getIQLReturnStatementAccess();
	}
	
	public ParserRule getIQLReturnStatementRule() {
		return getIQLReturnStatementAccess().getRule();
	}

	///////////////////////////////////////////////
	///////////////////////////////////////////////
	///////////////////////////////////////////////
	//IQLExpression:
	//	IQLAssignmentExpression;
	public BasicIQLGrammarAccess.IQLExpressionElements getIQLExpressionAccess() {
		return gaBasicIQL.getIQLExpressionAccess();
	}
	
	public ParserRule getIQLExpressionRule() {
		return getIQLExpressionAccess().getRule();
	}

	//OpAssign:
	//	"=" | "+=" | "-=" | "*=" | "/=" | "%=";
	public BasicIQLGrammarAccess.OpAssignElements getOpAssignAccess() {
		return gaBasicIQL.getOpAssignAccess();
	}
	
	public ParserRule getOpAssignRule() {
		return getOpAssignAccess().getRule();
	}

	//IQLLogicalOrExpression returns IQLExpression:
	//	IQLLogicalAndExpression (=> ({IQLLogicalOrExpression.leftOperand=current} op=OpLogicalOr)
	//	rightOperand=IQLLogicalAndExpression)*;
	public BasicIQLGrammarAccess.IQLLogicalOrExpressionElements getIQLLogicalOrExpressionAccess() {
		return gaBasicIQL.getIQLLogicalOrExpressionAccess();
	}
	
	public ParserRule getIQLLogicalOrExpressionRule() {
		return getIQLLogicalOrExpressionAccess().getRule();
	}

	//OpLogicalOr:
	//	"||";
	public BasicIQLGrammarAccess.OpLogicalOrElements getOpLogicalOrAccess() {
		return gaBasicIQL.getOpLogicalOrAccess();
	}
	
	public ParserRule getOpLogicalOrRule() {
		return getOpLogicalOrAccess().getRule();
	}

	//IQLLogicalAndExpression returns IQLExpression:
	//	IQLEqualityExpression (=> ({IQLLogicalAndExpression.leftOperand=current} op=OpLogicalAnd)
	//	rightOperand=IQLEqualityExpression)*;
	public BasicIQLGrammarAccess.IQLLogicalAndExpressionElements getIQLLogicalAndExpressionAccess() {
		return gaBasicIQL.getIQLLogicalAndExpressionAccess();
	}
	
	public ParserRule getIQLLogicalAndExpressionRule() {
		return getIQLLogicalAndExpressionAccess().getRule();
	}

	//OpLogicalAnd:
	//	"&&";
	public BasicIQLGrammarAccess.OpLogicalAndElements getOpLogicalAndAccess() {
		return gaBasicIQL.getOpLogicalAndAccess();
	}
	
	public ParserRule getOpLogicalAndRule() {
		return getOpLogicalAndAccess().getRule();
	}

	//IQLEqualityExpression returns IQLExpression:
	//	IQLRelationalExpression (=> ({IQLEqualityExpression.leftOperand=current} op=OpEquality)
	//	rightOperand=IQLRelationalExpression)*;
	public BasicIQLGrammarAccess.IQLEqualityExpressionElements getIQLEqualityExpressionAccess() {
		return gaBasicIQL.getIQLEqualityExpressionAccess();
	}
	
	public ParserRule getIQLEqualityExpressionRule() {
		return getIQLEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//	"==" | "!=";
	public BasicIQLGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaBasicIQL.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//IQLRelationalExpression returns IQLExpression:
	//	IQLAdditiveExpression (=> ({IQLInstanceOfExpression.leftOperand=current} "instanceof") targetRef=JvmTypeReference |
	//	=> ({IQLRelationalExpression.leftOperand=current} op=OpRelational) rightOperand=IQLAdditiveExpression)*;
	public BasicIQLGrammarAccess.IQLRelationalExpressionElements getIQLRelationalExpressionAccess() {
		return gaBasicIQL.getIQLRelationalExpressionAccess();
	}
	
	public ParserRule getIQLRelationalExpressionRule() {
		return getIQLRelationalExpressionAccess().getRule();
	}

	//OpRelational:
	//	">" | ">=" | "<" | "<=";
	public BasicIQLGrammarAccess.OpRelationalElements getOpRelationalAccess() {
		return gaBasicIQL.getOpRelationalAccess();
	}
	
	public ParserRule getOpRelationalRule() {
		return getOpRelationalAccess().getRule();
	}

	//IQLAdditiveExpression returns IQLExpression:
	//	IQLMultiplicativeExpression (=> ({IQLAdditiveExpression.leftOperand=current} op=OpAdd)
	//	rightOperand=IQLMultiplicativeExpression)*;
	public BasicIQLGrammarAccess.IQLAdditiveExpressionElements getIQLAdditiveExpressionAccess() {
		return gaBasicIQL.getIQLAdditiveExpressionAccess();
	}
	
	public ParserRule getIQLAdditiveExpressionRule() {
		return getIQLAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//	"+" | "-";
	public BasicIQLGrammarAccess.OpAddElements getOpAddAccess() {
		return gaBasicIQL.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//IQLMultiplicativeExpression returns IQLExpression:
	//	IQLUnaryExpression (=> ({IQLMultiplicativeExpression.leftOperand=current} op=OpMulti)
	//	rightOperand=IQLUnaryExpression)*;
	public BasicIQLGrammarAccess.IQLMultiplicativeExpressionElements getIQLMultiplicativeExpressionAccess() {
		return gaBasicIQL.getIQLMultiplicativeExpressionAccess();
	}
	
	public ParserRule getIQLMultiplicativeExpressionRule() {
		return getIQLMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//	"*" | "/" | "%";
	public BasicIQLGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaBasicIQL.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//IQLUnaryExpression returns IQLExpression:
	//	({IQLPlusMinusExpression} op=OpUnaryPlusMinus) operand=IQLMemberCallExpression | ({IQLBooleanNotExpression}
	//	op=OpUnaryBooleanNot) operand=IQLMemberCallExpression | ({IQLPrefixExpression} op=OpPrefix)
	//	operand=IQLMemberCallExpression | => ({IQLTypeCastExpression} "(" targetRef=JvmTypeReference ")")
	//	operand=IQLMemberCallExpression | IQLMemberCallExpression => ({IQLPostfixExpression.operand=current} op=OpPostfix)?;
	public BasicIQLGrammarAccess.IQLUnaryExpressionElements getIQLUnaryExpressionAccess() {
		return gaBasicIQL.getIQLUnaryExpressionAccess();
	}
	
	public ParserRule getIQLUnaryExpressionRule() {
		return getIQLUnaryExpressionAccess().getRule();
	}

	//OpUnaryPlusMinus:
	//	"-" | "+";
	public BasicIQLGrammarAccess.OpUnaryPlusMinusElements getOpUnaryPlusMinusAccess() {
		return gaBasicIQL.getOpUnaryPlusMinusAccess();
	}
	
	public ParserRule getOpUnaryPlusMinusRule() {
		return getOpUnaryPlusMinusAccess().getRule();
	}

	//OpUnaryBooleanNot:
	//	"!";
	public BasicIQLGrammarAccess.OpUnaryBooleanNotElements getOpUnaryBooleanNotAccess() {
		return gaBasicIQL.getOpUnaryBooleanNotAccess();
	}
	
	public ParserRule getOpUnaryBooleanNotRule() {
		return getOpUnaryBooleanNotAccess().getRule();
	}

	//OpPrefix:
	//	"++" | "--";
	public BasicIQLGrammarAccess.OpPrefixElements getOpPrefixAccess() {
		return gaBasicIQL.getOpPrefixAccess();
	}
	
	public ParserRule getOpPrefixRule() {
		return getOpPrefixAccess().getRule();
	}

	//OpPostfix:
	//	"++" | "--";
	public BasicIQLGrammarAccess.OpPostfixElements getOpPostfixAccess() {
		return gaBasicIQL.getOpPostfixAccess();
	}
	
	public ParserRule getOpPostfixRule() {
		return getOpPostfixAccess().getRule();
	}

	//IQLMemberCallExpression returns IQLExpression:
	//	IQLOtherExpressions (=> ({IQLArrayExpression.leftOperand=current} "[" expressions+=IQLExpression (","
	//	expressions+=IQLExpression)? "]") | => ({IQLMemberSelectionExpression.leftOperand=current} ".")
	//	sel=IQLMemberSelection)*;
	public BasicIQLGrammarAccess.IQLMemberCallExpressionElements getIQLMemberCallExpressionAccess() {
		return gaBasicIQL.getIQLMemberCallExpressionAccess();
	}
	
	public ParserRule getIQLMemberCallExpressionRule() {
		return getIQLMemberCallExpressionAccess().getRule();
	}

	//IQLMemberSelection:
	//	member=[types::JvmMember] args=IQLArgumentsList?;
	public BasicIQLGrammarAccess.IQLMemberSelectionElements getIQLMemberSelectionAccess() {
		return gaBasicIQL.getIQLMemberSelectionAccess();
	}
	
	public ParserRule getIQLMemberSelectionRule() {
		return getIQLMemberSelectionAccess().getRule();
	}

	//IQLOtherExpressions returns IQLExpression:
	//	{IQLJvmElementCallExpression} element=[types::JvmIdentifiableElement|QualifiedName] args=IQLArgumentsList? |
	//	{IQLThisExpression} "this" | {IQLSuperExpression} "super" | {IQLParenthesisExpression} "(" expr=IQLExpression ")" |
	//	{IQLNewExpression} "new" (ref=IQLArrayTypeRef | ref=IQLSimpleTypeRef argsList=IQLArgumentsList
	//	argsMap=IQLArgumentsMap?) | IQLLiteralExpression;
	public BasicIQLGrammarAccess.IQLOtherExpressionsElements getIQLOtherExpressionsAccess() {
		return gaBasicIQL.getIQLOtherExpressionsAccess();
	}
	
	public ParserRule getIQLOtherExpressionsRule() {
		return getIQLOtherExpressionsAccess().getRule();
	}

	//IQLLiteralExpression returns IQLExpression:
	//	{IQLLiteralExpressionInt} value=INT | {IQLLiteralExpressionDouble} value=DOUBLE | {IQLLiteralExpressionString}
	//	value=STRING | {IQLLiteralExpressionBoolean} value=BOOLEAN | {IQLLiteralExpressionRange} value=RANGE |
	//	{IQLLiteralExpressionNull} "null" | => IQLLiteralExpressionList | IQLLiteralExpressionMap;
	public BasicIQLGrammarAccess.IQLLiteralExpressionElements getIQLLiteralExpressionAccess() {
		return gaBasicIQL.getIQLLiteralExpressionAccess();
	}
	
	public ParserRule getIQLLiteralExpressionRule() {
		return getIQLLiteralExpressionAccess().getRule();
	}

	//IQLLiteralExpressionList returns IQLExpression:
	//	{IQLLiteralExpressionList} "[" (elements+=IQLExpression ("," elements+=IQLExpression)*)? "]";
	public BasicIQLGrammarAccess.IQLLiteralExpressionListElements getIQLLiteralExpressionListAccess() {
		return gaBasicIQL.getIQLLiteralExpressionListAccess();
	}
	
	public ParserRule getIQLLiteralExpressionListRule() {
		return getIQLLiteralExpressionListAccess().getRule();
	}

	//IQLLiteralExpressionMap returns IQLExpression:
	//	{IQLLiteralExpressionMap} "[" (elements+=IQLLiteralExpressionMapKeyValue (","
	//	elements+=IQLLiteralExpressionMapKeyValue)*)? "]";
	public BasicIQLGrammarAccess.IQLLiteralExpressionMapElements getIQLLiteralExpressionMapAccess() {
		return gaBasicIQL.getIQLLiteralExpressionMapAccess();
	}
	
	public ParserRule getIQLLiteralExpressionMapRule() {
		return getIQLLiteralExpressionMapAccess().getRule();
	}

	//IQLLiteralExpressionMapKeyValue:
	//	key=IQLExpression ":" value=IQLExpression;
	public BasicIQLGrammarAccess.IQLLiteralExpressionMapKeyValueElements getIQLLiteralExpressionMapKeyValueAccess() {
		return gaBasicIQL.getIQLLiteralExpressionMapKeyValueAccess();
	}
	
	public ParserRule getIQLLiteralExpressionMapKeyValueRule() {
		return getIQLLiteralExpressionMapKeyValueAccess().getRule();
	}

	///////////////////////////////////////////////
	///////////////////////////////////////////////
	///////////////////////////////////////////////
	//QualifiedNameWithWildcard:
	//	QualifiedName "::*"?;
	public BasicIQLGrammarAccess.QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return gaBasicIQL.getQualifiedNameWithWildcardAccess();
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//QualifiedName:
	//	ID ("::" ID)*;
	public BasicIQLGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaBasicIQL.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//terminal RANGE:
	//	INT ".." INT;
	public TerminalRule getRANGERule() {
		return gaBasicIQL.getRANGERule();
	} 

	//IQLJava:
	//	{IQLJava} (text+=IQLJavaText | keywords+=IQLJavaKeywords)*;
	public BasicIQLGrammarAccess.IQLJavaElements getIQLJavaAccess() {
		return gaBasicIQL.getIQLJavaAccess();
	}
	
	public ParserRule getIQLJavaRule() {
		return getIQLJavaAccess().getRule();
	}

	//IQLJavaText:
	//	ID | BOOLEAN | DOUBLE | STRING | INT | ANY_OTHER | "+" | "+=" | "-" | "-=" | "*" | "*=" | "/" | "/=" | "%" | "%=" |
	//	"++" | "--" | ">" | ">=" | "<" | "<=" | "!" | "!=" | "&&" | "||" | "==" | "=" | "~" | "?:" | "|" | "|=" | "^" | "^="
	//	| "&" | "&=" | ">>" | ">>=" | "<<" | "<<=" | ">>>" | ">>>=" | "[" | "]" | "{" | "}" | "(" | ")" | "." | ":" | ";" |
	//	"," | "null";
	public BasicIQLGrammarAccess.IQLJavaTextElements getIQLJavaTextAccess() {
		return gaBasicIQL.getIQLJavaTextAccess();
	}
	
	public ParserRule getIQLJavaTextRule() {
		return getIQLJavaTextAccess().getRule();
	}

	//IQLJavaKeywords:
	//	{IQLJavaKeywords} keyword=("break" | "case" | "class" | "continue" | "default" | "do" | "else" | "extends" | "for" |
	//	"if" | "implements" | "instanceof" | "interface" | "new" | "package" | "return" | "super" | "switch" | "this" |
	//	"while" | "abstract" | "assert" | "catch" | "const" | "enum" | "final" | "finally" | "goto" | "import" | "native" |
	//	"private" | "protected" | "public" | "static" | "synchronized" | "throw" | "throws" | "transient" | "try" |
	//	"volatile" | "strictfp");
	public BasicIQLGrammarAccess.IQLJavaKeywordsElements getIQLJavaKeywordsAccess() {
		return gaBasicIQL.getIQLJavaKeywordsAccess();
	}
	
	public ParserRule getIQLJavaKeywordsRule() {
		return getIQLJavaKeywordsAccess().getRule();
	}

	//terminal BOOLEAN returns ecore::EBoolean:
	//	"true" | "false";
	public TerminalRule getBOOLEANRule() {
		return gaBasicIQL.getBOOLEANRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaBasicIQL.getINTRule();
	} 

	//terminal DOUBLE returns ecore::EDouble:
	//	"0".."9"* "." "0".."9"+;
	public TerminalRule getDOUBLERule() {
		return gaBasicIQL.getDOUBLERule();
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaBasicIQL.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaBasicIQL.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaBasicIQL.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaBasicIQL.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaBasicIQL.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaBasicIQL.getANY_OTHERRule();
	} 
}
