/* Generated By:JJTree: Do not edit this line. ASTInsertIntoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniol.inf.is.odysseus.parser.cql.parser;

public
class ASTInsertIntoStatement extends SimpleNode {
  public ASTInsertIntoStatement(int id) {
    super(id);
  }

  public ASTInsertIntoStatement(NewSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(NewSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd2d98f3b80da83f28fbdad6101e0a9f (do not edit this line) */
