/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

package de.uniol.inf.is.odysseus.parser.cql.parser;

public class ASTIdentifier extends SimpleNode {
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ASTIdentifier(int id) {
		super(id);
	}

	public ASTIdentifier(NewSQLParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(NewSQLParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toString() {
		return name;
	}

	@Override
	public boolean equals(Object obj) {
		return this.name.equals(((ASTIdentifier) obj).name);
	}
	
	@Override
	public int hashCode() {
		return this.name.hashCode();
	}
}
