/* Generated By:JavaCC: Do not edit this line. NewSQLParserTreeConstants.java Version 5.0 */
package de.uniol.inf.is.odysseus.parser.cql.parser;

public interface NewSQLParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTPRIORIZEDSTATEMENT = 1;
  public int JJTSTREAMTOSTATEMENT = 2;
  public int JJTCOMPLEXSELECTSTATEMENT = 3;
  public int JJTSELECTSTATEMENT = 4;
  public int JJTCREATETYPE = 5;
  public int JJTCREATESTATEMENT = 6;
  public int JJTLOGINPASSWORD = 7;
  public int JJTCREATESINKSTATEMENT = 8;
  public int JJTSOCKETSINK = 9;
  public int JJTDATABASESINK = 10;
  public int JJTDATABASESINKOPTIONS = 11;
  public int JJTFILESINK = 12;
  public int JJTCREATEDATABASECONNECTION = 13;
  public int JJTCREATEFROMDATABASE = 14;
  public int JJTDATABASETIMESENSITIV = 15;
  public int JJTCREATEVIEWSTATEMENT = 16;
  public int JJTCREATESENSOR = 17;
  public int JJTORSCHEMADEFINITION = 18;
  public int JJTRECORDDEFINITION = 19;
  public int JJTRECORDENTRYDEFINITION = 20;
  public int JJTLISTDEFINITION = 21;
  public int JJTATTRDEFINITION = 22;
  public int JJTATTRIBUTEDEFINITIONS = 23;
  public int JJTATTRIBUTEDEFINITION = 24;
  public int JJTTIMEDTUPLES = 25;
  public int JJTTIMEDTUPLE = 26;
  public int JJTTIMEINTERVAL = 27;
  public int JJTSOCKET = 28;
  public int JJTSILAB = 29;
  public int JJTCHANNEL = 30;
  public int JJTAUTORECONNECT = 31;
  public int JJTHOST = 32;
  public int JJTFILESOURCE = 33;
  public int JJTSIMPLETUPLE = 34;
  public int JJTVOID = 35;
  public int JJTATTRIBUTETYPE = 36;
  public int JJTMVCOVARIANCEROW = 37;
  public int JJTCOVARIANCEROW = 38;
  public int JJTDATEFORMAT = 39;
  public int JJTSETOPERATOR = 40;
  public int JJTSELECTCLAUSE = 41;
  public int JJTPROJECTIONMATRIX = 42;
  public int JJTPROJECTIONVECTOR = 43;
  public int JJTFROMCLAUSE = 44;
  public int JJTWHERECLAUSE = 45;
  public int JJTGROUPBYCLAUSE = 46;
  public int JJTHAVINGCLAUSE = 47;
  public int JJTSELECTALL = 48;
  public int JJTRENAMEDEXPRESSION = 49;
  public int JJTAS = 50;
  public int JJTMATRIXEXPRESSION = 51;
  public int JJTPREDICATE = 52;
  public int JJTSIMPLEPREDICATE = 53;
  public int JJTBASICPREDICATE = 54;
  public int JJTPROBABILITYPREDICATE = 55;
  public int JJTPRIORITY = 56;
  public int JJTORPREDICATE = 57;
  public int JJTANDPREDICATE = 58;
  public int JJTNOTPREDICATE = 59;
  public int JJTQUANTIFICATIONPREDICATE = 60;
  public int JJTANYPREDICATE = 61;
  public int JJTALLPREDICATE = 62;
  public int JJTINPREDICATE = 63;
  public int JJTEXISTS = 64;
  public int JJTELEMENTPRIORITIES = 65;
  public int JJTELEMENTPRIORITY = 66;
  public int JJTDEFAULTPRIORITY = 67;
  public int JJTTUPLE = 68;
  public int JJTTIME = 69;
  public int JJTTUPLESET = 70;
  public int JJTQUANTIFICATIONOPERATOR = 71;
  public int JJTEXPRESSION = 72;
  public int JJTSIMPLETOKEN = 73;
  public int JJTFUNCTIONEXPRESSION = 74;
  public int JJTFUNCTIONNAME = 75;
  public int JJTAGGREGATEEXPRESSION = 76;
  public int JJTAGGREGATEFUNCTION = 77;
  public int JJTDISTINCTEXPRESSION = 78;
  public int JJTSIMPLESOURCE = 79;
  public int JJTSUBSELECT = 80;
  public int JJTSTREAMSQLWINDOW = 81;
  public int JJTPARTITION = 82;
  public int JJTADVANCE = 83;
  public int JJTSLIDE = 84;
  public int JJTIDENTIFIER = 85;
  public int JJTINTEGER = 86;
  public int JJTNUMBER = 87;
  public int JJTSTRING = 88;
  public int JJTCOMPAREOPERATOR = 89;
  public int JJTSPATIALCOMPAREOPERATOR = 90;
  public int JJTCREATEBROKER = 91;
  public int JJTBROKERSOURCE = 92;
  public int JJTBROKERASSOURCE = 93;
  public int JJTBROKERSELECTINTO = 94;
  public int JJTBROKERSIMPLESOURCE = 95;
  public int JJTBROKERQUEUE = 96;
  public int JJTMETRIC = 97;
  public int JJTCREATEUSERSTATEMENT = 98;
  public int JJTALTERUSERSTATEMENT = 99;
  public int JJTDROPUSERSTATEMENT = 100;
  public int JJTCREATESLASTATEMENT = 101;
  public int JJTSLAMETRICDEF = 102;
  public int JJTSLASCOPEDEF = 103;
  public int JJTSLAWINDOWDEF = 104;
  public int JJTSLASERVICELEVELDEF = 105;
  public int JJTSLAPENALTYDEF = 106;
  public int JJTDROPSTREAMSTATEMENT = 107;
  public int JJTDROPVIEWSTATEMENT = 108;
  public int JJTCREATEROLESTATEMENT = 109;
  public int JJTIFEXISTS = 110;
  public int JJTDROPROLESTATEMENT = 111;
  public int JJTGRANTROLESTATEMENT = 112;
  public int JJTREVOKEROLESTATEMENT = 113;
  public int JJTGRANTSTATEMENT = 114;
  public int JJTIDENTIFIERLIST = 115;
  public int JJTREVOKESTATEMENT = 116;


  public String[] jjtNodeName = {
    "Statement",
    "PriorizedStatement",
    "StreamToStatement",
    "ComplexSelectStatement",
    "SelectStatement",
    "CreateType",
    "CreateStatement",
    "LoginPassword",
    "CreateSinkStatement",
    "SocketSink",
    "DatabaseSink",
    "DatabaseSinkOptions",
    "FileSink",
    "CreateDatabaseConnection",
    "CreateFromDatabase",
    "DatabaseTimeSensitiv",
    "CreateViewStatement",
    "CreateSensor",
    "ORSchemaDefinition",
    "RecordDefinition",
    "RecordEntryDefinition",
    "ListDefinition",
    "AttrDefinition",
    "AttributeDefinitions",
    "AttributeDefinition",
    "TimedTuples",
    "TimedTuple",
    "TimeInterval",
    "Socket",
    "Silab",
    "Channel",
    "AutoReconnect",
    "Host",
    "FileSource",
    "SimpleTuple",
    "void",
    "AttributeType",
    "MVCovarianceRow",
    "CovarianceRow",
    "DateFormat",
    "SetOperator",
    "SelectClause",
    "ProjectionMatrix",
    "ProjectionVector",
    "FromClause",
    "WhereClause",
    "GroupByClause",
    "HavingClause",
    "SelectAll",
    "RenamedExpression",
    "AS",
    "MatrixExpression",
    "Predicate",
    "SimplePredicate",
    "BasicPredicate",
    "ProbabilityPredicate",
    "Priority",
    "OrPredicate",
    "AndPredicate",
    "NotPredicate",
    "QuantificationPredicate",
    "AnyPredicate",
    "AllPredicate",
    "InPredicate",
    "Exists",
    "ElementPriorities",
    "ElementPriority",
    "DefaultPriority",
    "Tuple",
    "Time",
    "TupleSet",
    "QuantificationOperator",
    "Expression",
    "SimpleToken",
    "FunctionExpression",
    "FunctionName",
    "AggregateExpression",
    "AggregateFunction",
    "DistinctExpression",
    "SimpleSource",
    "Subselect",
    "StreamSQLWindow",
    "Partition",
    "Advance",
    "Slide",
    "Identifier",
    "Integer",
    "Number",
    "String",
    "CompareOperator",
    "SpatialCompareOperator",
    "CreateBroker",
    "BrokerSource",
    "BrokerAsSource",
    "BrokerSelectInto",
    "BrokerSimpleSource",
    "BrokerQueue",
    "Metric",
    "CreateUserStatement",
    "AlterUserStatement",
    "DropUserStatement",
    "CreateSLAStatement",
    "SlaMetricDef",
    "SlaScopeDef",
    "SlaWindowDef",
    "SlaServiceLevelDef",
    "SlaPenaltyDef",
    "DropStreamStatement",
    "DropViewStatement",
    "CreateRoleStatement",
    "IfExists",
    "DropRoleStatement",
    "GrantRoleStatement",
    "RevokeRoleStatement",
    "GrantStatement",
    "IdentifierList",
    "RevokeStatement",
  };
}
/* JavaCC - OriginalChecksum=d5f1cde75fab39d3e1593965fddacfd7 (do not edit this line) */
