/* Generated By:JJTree&JavaCC: Do not edit this line. NewSQLParserConstants.java */
package de.uniol.inf.is.odysseus.parser.cql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewSQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ALL = 5;
  /** RegularExpression Id. */
  int K_ADD = 6;
  /** RegularExpression Id. */
  int K_ADVANCE = 7;
  /** RegularExpression Id. */
  int K_ALTER = 8;
  /** RegularExpression Id. */
  int K_ALWAYS = 9;
  /** RegularExpression Id. */
  int K_AND = 10;
  /** RegularExpression Id. */
  int K_ANY = 11;
  /** RegularExpression Id. */
  int K_AS = 12;
  /** RegularExpression Id. */
  int K_ATTACH = 13;
  /** RegularExpression Id. */
  int K_AVG = 14;
  /** RegularExpression Id. */
  int K_BROKER = 15;
  /** RegularExpression Id. */
  int K_BY = 16;
  /** RegularExpression Id. */
  int K_CHANNEL = 17;
  /** RegularExpression Id. */
  int K_COMMENT = 18;
  /** RegularExpression Id. */
  int K_COUNT = 19;
  /** RegularExpression Id. */
  int K_CREATE = 20;
  /** RegularExpression Id. */
  int K_CSV = 21;
  /** RegularExpression Id. */
  int K_DBTABLE = 22;
  /** RegularExpression Id. */
  int K_DATE = 23;
  /** RegularExpression Id. */
  int K_DAY = 24;
  /** RegularExpression Id. */
  int K_DB_EXECUTE = 25;
  /** RegularExpression Id. */
  int K_DB_SELECT = 26;
  /** RegularExpression Id. */
  int K_DB_SCHEMA = 27;
  /** RegularExpression Id. */
  int K_DEFAULT = 28;
  /** RegularExpression Id. */
  int K_DISTINCT = 29;
  /** RegularExpression Id. */
  int K_DETACH = 30;
  /** RegularExpression Id. */
  int K_DOUBLE = 31;
  /** RegularExpression Id. */
  int K_DROP = 32;
  /** RegularExpression Id. */
  int K_END_TIMESTAMP = 33;
  /** RegularExpression Id. */
  int K_EXISTS = 34;
  /** RegularExpression Id. */
  int K_FLOAT = 35;
  /** RegularExpression Id. */
  int K_FROM = 36;
  /** RegularExpression Id. */
  int K_GROUP = 37;
  /** RegularExpression Id. */
  int K_HAVING = 38;
  /** RegularExpression Id. */
  int K_HOUR = 39;
  /** RegularExpression Id. */
  int K_IDENTIFIED = 40;
  /** RegularExpression Id. */
  int K_IN = 41;
  /** RegularExpression Id. */
  int K_INFTY = 42;
  /** RegularExpression Id. */
  int K_INTEGER = 43;
  /** RegularExpression Id. */
  int K_INTERSECTION = 44;
  /** RegularExpression Id. */
  int K_INTO = 45;
  /** RegularExpression Id. */
  int K_IS = 46;
  /** RegularExpression Id. */
  int K_JOIN = 47;
  /** RegularExpression Id. */
  int K_LIKE = 48;
  /** RegularExpression Id. */
  int K_LONG = 49;
  /** RegularExpression Id. */
  int K_MATRIX = 50;
  /** RegularExpression Id. */
  int K_MAX = 51;
  /** RegularExpression Id. */
  int K_METRIC = 52;
  /** RegularExpression Id. */
  int K_MIN = 53;
  /** RegularExpression Id. */
  int K_MINUS = 54;
  /** RegularExpression Id. */
  int K_MINUTE = 55;
  /** RegularExpression Id. */
  int K_MV = 56;
  /** RegularExpression Id. */
  int K_NATURAL = 57;
  /** RegularExpression Id. */
  int K_NOT = 58;
  /** RegularExpression Id. */
  int K_NULL = 59;
  /** RegularExpression Id. */
  int K_OF = 60;
  /** RegularExpression Id. */
  int K_OFFSET = 61;
  /** RegularExpression Id. */
  int K_ON = 62;
  /** RegularExpression Id. */
  int K_OR = 63;
  /** RegularExpression Id. */
  int K_OSGI = 64;
  /** RegularExpression Id. */
  int K_OUTPUT = 65;
  /** RegularExpression Id. */
  int K_PARTITION = 66;
  /** RegularExpression Id. */
  int K_PRIORITY = 67;
  /** RegularExpression Id. */
  int K_PROB = 68;
  /** RegularExpression Id. */
  int K_QUEUE = 69;
  /** RegularExpression Id. */
  int K_RANGE = 70;
  /** RegularExpression Id. */
  int K_REAL = 71;
  /** RegularExpression Id. */
  int K_RELATION = 72;
  /** RegularExpression Id. */
  int K_RELATIVE = 73;
  /** RegularExpression Id. */
  int K_REMOVE = 74;
  /** RegularExpression Id. */
  int K_ROWS = 75;
  /** RegularExpression Id. */
  int K_SECOND = 76;
  /** RegularExpression Id. */
  int K_SELECT = 77;
  /** RegularExpression Id. */
  int K_SET = 78;
  /** RegularExpression Id. */
  int K_SILAB = 79;
  /** RegularExpression Id. */
  int K_SIZE = 80;
  /** RegularExpression Id. */
  int K_SLA = 81;
  /** RegularExpression Id. */
  int K_SLIDE = 82;
  /** RegularExpression Id. */
  int K_SOCKET = 83;
  /** RegularExpression Id. */
  int K_START_TIMESTAMP = 84;
  /** RegularExpression Id. */
  int K_STREAM = 85;
  /** RegularExpression Id. */
  int K_STRING = 86;
  /** RegularExpression Id. */
  int K_SUM = 87;
  /** RegularExpression Id. */
  int K_TENANT = 88;
  /** RegularExpression Id. */
  int K_TIME = 89;
  /** RegularExpression Id. */
  int K_TIMEOUT = 90;
  /** RegularExpression Id. */
  int K_TO = 91;
  /** RegularExpression Id. */
  int K_TUPLE = 92;
  /** RegularExpression Id. */
  int K_UNBOUNDED = 93;
  /** RegularExpression Id. */
  int K_UNION = 94;
  /** RegularExpression Id. */
  int K_USER = 95;
  /** RegularExpression Id. */
  int K_VALID = 96;
  /** RegularExpression Id. */
  int K_VIEW = 97;
  /** RegularExpression Id. */
  int K_WEEK = 98;
  /** RegularExpression Id. */
  int K_WHERE = 99;
  /** RegularExpression Id. */
  int K_WITH = 100;
  /** RegularExpression Id. */
  int K_SENSOR = 101;
  /** RegularExpression Id. */
  int K_ATTRIBUTE = 102;
  /** RegularExpression Id. */
  int K_RECORD = 103;
  /** RegularExpression Id. */
  int K_LIST = 104;
  /** RegularExpression Id. */
  int S_DISTANCE = 105;
  /** RegularExpression Id. */
  int S_COMPARE = 106;
  /** RegularExpression Id. */
  int S_POINT = 107;
  /** RegularExpression Id. */
  int S_SEGMENT = 108;
  /** RegularExpression Id. */
  int S_LINE = 109;
  /** RegularExpression Id. */
  int S_FACET = 110;
  /** RegularExpression Id. */
  int S_SOLID = 111;
  /** RegularExpression Id. */
  int FLOAT = 112;
  /** RegularExpression Id. */
  int INTEGER = 113;
  /** RegularExpression Id. */
  int DIGIT = 114;
  /** RegularExpression Id. */
  int IPADDRESS = 115;
  /** RegularExpression Id. */
  int LINE_COMMENT = 116;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 117;
  /** RegularExpression Id. */
  int IDENTIFIER = 118;
  /** RegularExpression Id. */
  int LETTER = 119;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 120;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 121;
  /** RegularExpression Id. */
  int SQL_STRING = 122;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 123;
  /** RegularExpression Id. */
  int COMPARE_OPERATOR = 124;
  /** RegularExpression Id. */
  int REGEXP = 125;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"ALL\"",
    "\"ADD\"",
    "\"ADVANCE\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ATTACH\"",
    "\"AVG\"",
    "\"BROKER\"",
    "\"BY\"",
    "\"CHANNEL\"",
    "\"COMMENT\"",
    "\"COUNT\"",
    "\"CREATE\"",
    "\"CSV\"",
    "\"DBTABLE\"",
    "\"DATE\"",
    "<K_DAY>",
    "\"DB_EXECUTE\"",
    "\"DATABASE\"",
    "\"SCHEMA\"",
    "\"DEFAULT\"",
    "\"DISTINCT\"",
    "\"DETACH\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"ENDTIMESTAMP\"",
    "\"EXISTS\"",
    "\"FLOAT\"",
    "\"FROM\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "<K_HOUR>",
    "\"IDENTIFIED\"",
    "\"IN\"",
    "\"INFTY\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"JOIN\"",
    "\"LIKE\"",
    "\"LONG\"",
    "\"MATRIX\"",
    "\"MAX\"",
    "\"METRIC\"",
    "\"MIN\"",
    "\"MINUS\"",
    "<K_MINUTE>",
    "\"MV\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"ON\"",
    "\"OR\"",
    "\"OSGI\"",
    "\"OUTPUT\"",
    "\"PARTITION\"",
    "\"PRIORITY\"",
    "\"PROB\"",
    "\"QUEUE\"",
    "\"RANGE\"",
    "\"REAL\"",
    "\"RELATION\"",
    "\"RELATIVE\"",
    "\"REMOVE\"",
    "\"ROWS\"",
    "<K_SECOND>",
    "\"SELECT\"",
    "\"SET\"",
    "\"SILAB\"",
    "\"SIZE\"",
    "\"SLA\"",
    "\"SLIDE\"",
    "\"SOCKET\"",
    "\"STARTTIMESTAMP\"",
    "\"STREAM\"",
    "\"STRING\"",
    "\"SUM\"",
    "\"TENANT\"",
    "\"TIME\"",
    "\"TIMEOUT\"",
    "\"TO\"",
    "\"TUPLE\"",
    "\"UNBOUNDED\"",
    "\"UNION\"",
    "\"USER\"",
    "\"VALID\"",
    "\"VIEW\"",
    "<K_WEEK>",
    "\"WHERE\"",
    "\"WITH\"",
    "\"SENSOR\"",
    "\"ATTRIBUTE\"",
    "\"RECORD\"",
    "\"LIST\"",
    "\"SPATIAL_DISTANCE\"",
    "<S_COMPARE>",
    "\"POINT3D\"",
    "\"SEGMENT3D\"",
    "\"LINE3D\"",
    "\"FACET3D\"",
    "\"SOLID3D\"",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<IPADDRESS>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<CHAR_LITERAL>",
    "<SQL_STRING>",
    "<QUOTED_IDENTIFIER>",
    "<COMPARE_OPERATOR>",
    "<REGEXP>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"-\"",
    "\":\"",
    "\"*\"",
    "\"]\"",
    "\"+\"",
    "\"/\"",
    "\"^\"",
  };

}
