/* Generated By:JJTree&JavaCC: Do not edit this line. NewSQLParserConstants.java */
package de.uniol.inf.is.odysseus.parser.cql.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface NewSQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ALL = 5;
  /** RegularExpression Id. */
  int K_ADD = 6;
  /** RegularExpression Id. */
  int K_ADVANCE = 7;
  /** RegularExpression Id. */
  int K_ALTER = 8;
  /** RegularExpression Id. */
  int K_ALWAYS = 9;
  /** RegularExpression Id. */
  int K_AND = 10;
  /** RegularExpression Id. */
  int K_ANY = 11;
  /** RegularExpression Id. */
  int K_AS = 12;
  /** RegularExpression Id. */
  int K_ASSIGN = 13;
  /** RegularExpression Id. */
  int K_AT = 14;
  /** RegularExpression Id. */
  int K_ATTACH = 15;
  /** RegularExpression Id. */
  int K_AUTO_RECONNECT = 16;
  /** RegularExpression Id. */
  int K_AVG = 17;
  /** RegularExpression Id. */
  int K_BROKER = 18;
  /** RegularExpression Id. */
  int K_BY = 19;
  /** RegularExpression Id. */
  int K_CHANNEL = 20;
  /** RegularExpression Id. */
  int K_CHECK = 21;
  /** RegularExpression Id. */
  int K_CONTEXT = 22;
  /** RegularExpression Id. */
  int K_COMMENT = 23;
  /** RegularExpression Id. */
  int K_CONNECTION = 24;
  /** RegularExpression Id. */
  int K_COUNT = 25;
  /** RegularExpression Id. */
  int K_CREATE = 26;
  /** RegularExpression Id. */
  int K_DATABASE = 27;
  /** RegularExpression Id. */
  int K_DAY = 28;
  /** RegularExpression Id. */
  int K_DEFAULT = 29;
  /** RegularExpression Id. */
  int K_DELETE = 30;
  /** RegularExpression Id. */
  int K_DISTINCT = 31;
  /** RegularExpression Id. */
  int K_DETACH = 32;
  /** RegularExpression Id. */
  int K_DROP = 33;
  /** RegularExpression Id. */
  int K_EACH = 34;
  /** RegularExpression Id. */
  int K_EXISTS = 35;
  /** RegularExpression Id. */
  int K_FILE = 36;
  /** RegularExpression Id. */
  int K_FROM = 37;
  /** RegularExpression Id. */
  int K_GRANT = 38;
  /** RegularExpression Id. */
  int K_GROUP = 39;
  /** RegularExpression Id. */
  int K_HAVING = 40;
  /** RegularExpression Id. */
  int K_HOUR = 41;
  /** RegularExpression Id. */
  int K_IDENTIFIED = 42;
  /** RegularExpression Id. */
  int K_IF = 43;
  /** RegularExpression Id. */
  int K_IN = 44;
  /** RegularExpression Id. */
  int K_INFTY = 45;
  /** RegularExpression Id. */
  int K_INSERT = 46;
  /** RegularExpression Id. */
  int K_INTERSECTION = 47;
  /** RegularExpression Id. */
  int K_INTO = 48;
  /** RegularExpression Id. */
  int K_IS = 49;
  /** RegularExpression Id. */
  int K_JDBC = 50;
  /** RegularExpression Id. */
  int K_JOIN = 51;
  /** RegularExpression Id. */
  int K_KILL = 52;
  /** RegularExpression Id. */
  int K_KEY = 53;
  /** RegularExpression Id. */
  int K_LAZY_CONNECTION_CHECK = 54;
  /** RegularExpression Id. */
  int K_LIKE = 55;
  /** RegularExpression Id. */
  int K_LINEAR_STORE = 56;
  /** RegularExpression Id. */
  int K_LOGARITHMIC_STORE = 57;
  /** RegularExpression Id. */
  int K_LOGIN_REQUIRED = 58;
  /** RegularExpression Id. */
  int K_MATRIX = 59;
  /** RegularExpression Id. */
  int K_MAX = 60;
  /** RegularExpression Id. */
  int K_MAX_ADMISSION_COST_FACTOR = 61;
  /** RegularExpression Id. */
  int K_METADATA = 62;
  /** RegularExpression Id. */
  int K_METRIC = 63;
  /** RegularExpression Id. */
  int K_MILLISECOND = 64;
  /** RegularExpression Id. */
  int K_MIN = 65;
  /** RegularExpression Id. */
  int K_MINUS = 66;
  /** RegularExpression Id. */
  int K_MINUTE = 67;
  /** RegularExpression Id. */
  int K_MULTI = 68;
  /** RegularExpression Id. */
  int K_MV = 69;
  /** RegularExpression Id. */
  int K_NATURAL = 70;
  /** RegularExpression Id. */
  int K_NO_LAZY_CONNECTION_CHECK = 71;
  /** RegularExpression Id. */
  int K_NOT = 72;
  /** RegularExpression Id. */
  int K_NULL = 73;
  /** RegularExpression Id. */
  int K_OF = 74;
  /** RegularExpression Id. */
  int K_OFFSET = 75;
  /** RegularExpression Id. */
  int K_ON = 76;
  /** RegularExpression Id. */
  int K_OR = 77;
  /** RegularExpression Id. */
  int K_OUTPUT = 78;
  /** RegularExpression Id. */
  int K_PARTITION = 79;
  /** RegularExpression Id. */
  int K_PASSWORD = 80;
  /** RegularExpression Id. */
  int K_PENALTY = 81;
  /** RegularExpression Id. */
  int K_PRIORITY = 82;
  /** RegularExpression Id. */
  int K_PROB = 83;
  /** RegularExpression Id. */
  int K_QUEUE = 84;
  /** RegularExpression Id. */
  int K_RANGE = 85;
  /** RegularExpression Id. */
  int K_RELATION = 86;
  /** RegularExpression Id. */
  int K_RELATIVE = 87;
  /** RegularExpression Id. */
  int K_REMOVE = 88;
  /** RegularExpression Id. */
  int K_REVOKE = 89;
  /** RegularExpression Id. */
  int K_ROLE = 90;
  /** RegularExpression Id. */
  int K_ROWS = 91;
  /** RegularExpression Id. */
  int K_SCOPE = 92;
  /** RegularExpression Id. */
  int K_SECOND = 93;
  /** RegularExpression Id. */
  int K_SELECT = 94;
  /** RegularExpression Id. */
  int K_SERVICE_LEVEL = 95;
  /** RegularExpression Id. */
  int K_SET = 96;
  /** RegularExpression Id. */
  int K_SILAB = 97;
  /** RegularExpression Id. */
  int K_SINGLE = 98;
  /** RegularExpression Id. */
  int K_SINK = 99;
  /** RegularExpression Id. */
  int K_SIZE = 100;
  /** RegularExpression Id. */
  int K_SLA = 101;
  /** RegularExpression Id. */
  int K_SLIDE = 102;
  /** RegularExpression Id. */
  int K_SOCKET = 103;
  /** RegularExpression Id. */
  int K_STORE = 104;
  /** RegularExpression Id. */
  int K_STREAM = 105;
  /** RegularExpression Id. */
  int K_SUM = 106;
  /** RegularExpression Id. */
  int K_TABLE = 107;
  /** RegularExpression Id. */
  int K_TIME = 108;
  /** RegularExpression Id. */
  int K_TIME_SENSITIV = 109;
  /** RegularExpression Id. */
  int K_TIMEOUT = 110;
  /** RegularExpression Id. */
  int K_TO = 111;
  /** RegularExpression Id. */
  int K_TRUNCATE = 112;
  /** RegularExpression Id. */
  int K_TUPLE = 113;
  /** RegularExpression Id. */
  int K_TYPE = 114;
  /** RegularExpression Id. */
  int K_UNBOUNDED = 115;
  /** RegularExpression Id. */
  int K_UNION = 116;
  /** RegularExpression Id. */
  int K_USE = 117;
  /** RegularExpression Id. */
  int K_USER = 118;
  /** RegularExpression Id. */
  int K_VALID = 119;
  /** RegularExpression Id. */
  int K_VIEW = 120;
  /** RegularExpression Id. */
  int K_WEEK = 121;
  /** RegularExpression Id. */
  int K_WHERE = 122;
  /** RegularExpression Id. */
  int K_WITH = 123;
  /** RegularExpression Id. */
  int K_SENSOR = 124;
  /** RegularExpression Id. */
  int K_ATTRIBUTE = 125;
  /** RegularExpression Id. */
  int K_RECORD = 126;
  /** RegularExpression Id. */
  int K_LIST = 127;
  /** RegularExpression Id. */
  int S_DISTANCE = 128;
  /** RegularExpression Id. */
  int S_COMPARE = 129;
  /** RegularExpression Id. */
  int S_POINT = 130;
  /** RegularExpression Id. */
  int S_LINE = 131;
  /** RegularExpression Id. */
  int S_POLYGON = 132;
  /** RegularExpression Id. */
  int S_MULTI_POINT = 133;
  /** RegularExpression Id. */
  int S_MULTI_LINE = 134;
  /** RegularExpression Id. */
  int S_MULTI_POLYGON = 135;
  /** RegularExpression Id. */
  int SPATIAL = 136;
  /** RegularExpression Id. */
  int FLOAT = 137;
  /** RegularExpression Id. */
  int INTEGER = 138;
  /** RegularExpression Id. */
  int DIGIT = 139;
  /** RegularExpression Id. */
  int IPADDRESS = 140;
  /** RegularExpression Id. */
  int LINE_COMMENT = 141;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 142;
  /** RegularExpression Id. */
  int JDBC_STRING = 143;
  /** RegularExpression Id. */
  int IDENTIFIER = 144;
  /** RegularExpression Id. */
  int LETTER = 145;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 146;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 147;
  /** RegularExpression Id. */
  int SQL_STRING = 148;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 149;
  /** RegularExpression Id. */
  int COMPARE_OPERATOR = 150;
  /** RegularExpression Id. */
  int REGEXP = 151;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"ALL\"",
    "\"ADD\"",
    "\"ADVANCE\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASSIGN\"",
    "\"AT\"",
    "\"ATTACH\"",
    "\"AUTORECONNECT\"",
    "\"AVG\"",
    "\"BROKER\"",
    "\"BY\"",
    "\"CHANNEL\"",
    "\"CHECK\"",
    "\"CONTEXT\"",
    "\"COMMENT\"",
    "\"CONNECTION\"",
    "\"COUNT\"",
    "\"CREATE\"",
    "\"DATABASE\"",
    "<K_DAY>",
    "\"DEFAULT\"",
    "\"DELETE\"",
    "\"DISTINCT\"",
    "\"DETACH\"",
    "\"DROP\"",
    "\"EACH\"",
    "\"EXISTS\"",
    "\"FILE\"",
    "\"FROM\"",
    "\"GRANT\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "<K_HOUR>",
    "\"IDENTIFIED\"",
    "\"IF\"",
    "\"IN\"",
    "\"INFTY\"",
    "\"INSERT\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"JDBC\"",
    "\"JOIN\"",
    "\"KILL\"",
    "\"KEY\"",
    "\"LAZY_CONNECTION_CHECK\"",
    "\"LIKE\"",
    "\"LINEAR_STORE\"",
    "\"LOGARITHMIC_STORE\"",
    "\"LOGIN_REQUIRED\"",
    "\"MATRIX\"",
    "\"MAX\"",
    "\"MAX_ADMISSION_COST_FACTOR\"",
    "\"METADATA\"",
    "\"METRIC\"",
    "<K_MILLISECOND>",
    "\"MIN\"",
    "\"MINUS\"",
    "<K_MINUTE>",
    "\"MULTI\"",
    "\"MV\"",
    "\"NATURAL\"",
    "\"NO_LAZY_CONNECTION_CHECK\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"ON\"",
    "\"OR\"",
    "\"OUTPUT\"",
    "\"PARTITION\"",
    "\"PASSWORD\"",
    "\"PENALTY\"",
    "\"PRIORITY\"",
    "\"PROB\"",
    "\"QUEUE\"",
    "\"RANGE\"",
    "\"RELATION\"",
    "\"RELATIVE\"",
    "\"REMOVE\"",
    "\"REVOKE\"",
    "\"ROLE\"",
    "\"ROWS\"",
    "\"SCOPE\"",
    "<K_SECOND>",
    "\"SELECT\"",
    "\"SERVICELEVEL\"",
    "\"SET\"",
    "\"SILAB\"",
    "\"SINGLE\"",
    "\"SINK\"",
    "\"SIZE\"",
    "\"SLA\"",
    "\"SLIDE\"",
    "\"SOCKET\"",
    "\"STORE\"",
    "\"STREAM\"",
    "\"SUM\"",
    "\"TABLE\"",
    "\"TIME\"",
    "\"TIMESENSITIV\"",
    "\"TIMEOUT\"",
    "\"TO\"",
    "\"TRUNCATE\"",
    "\"TUPLE\"",
    "\"TYPE\"",
    "\"UNBOUNDED\"",
    "\"UNION\"",
    "\"USE\"",
    "\"USER\"",
    "\"VALID\"",
    "\"VIEW\"",
    "<K_WEEK>",
    "\"WHERE\"",
    "\"WITH\"",
    "\"SENSOR\"",
    "\"ATTRIBUTE\"",
    "\"RECORD\"",
    "\"LIST\"",
    "\"SPATIAL_DISTANCE\"",
    "<S_COMPARE>",
    "\"SPATIAL_POINT\"",
    "\"SPATIAL_LINE\"",
    "\"SPATIAL_POLYGON\"",
    "\"SPATIAL_MULTI_POINT\"",
    "\"SPATIAL_MULTI_LINE\"",
    "\"SPATIAL_MULTI_POLYGON\"",
    "\"SPATIAL\"",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<IPADDRESS>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<JDBC_STRING>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<CHAR_LITERAL>",
    "<SQL_STRING>",
    "<QUOTED_IDENTIFIER>",
    "<COMPARE_OPERATOR>",
    "<REGEXP>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
    "\"[\"",
    "\"-\"",
    "\"*\"",
    "\"]\"",
    "\"+\"",
    "\"/\"",
    "\"^\"",
  };

}
