/**
 * generated by Xtext 2.10.0
 */
package de.uniol.inf.is.odysseus.parser.novel.cql.cQL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Component As Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.uniol.inf.is.odysseus.parser.novel.cql.cQL.CQLPackage#getExpressionComponentAsAttribute()
 * @model
 * @generated
 */
public interface ExpressionComponentAsAttribute extends ExpressionComponent
{
} // ExpressionComponentAsAttribute
