/* Generated By:JavaCC: Do not edit this line. MEPImplTreeConstants.java Version 5.0 */
package de.uniol.inf.is.odysseus.core.server.mep.impl;

public interface MEPImplTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTFUNCTION = 2;
  public int JJTCONSTANT = 3;
  public int JJTVARIABLE = 4;
  public int JJTMATRIX = 5;
  public int JJTMATRIXLINE = 6;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Function",
    "Constant",
    "Variable",
    "Matrix",
    "MatrixLine",
  };
}
/* JavaCC - OriginalChecksum=d89c50f83b278d6df225d48ca1a6d779 (do not edit this line) */
