/*
 * generated by Xtext 2.10.0
 */
package de.uniol.inf.is.odysseus.parser.novel.cql.parser.antlr;

import com.google.inject.Inject;
import de.uniol.inf.is.odysseus.parser.novel.cql.parser.antlr.internal.InternalCqlParser;
import de.uniol.inf.is.odysseus.parser.novel.cql.services.CqlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CqlParser extends AbstractAntlrParser {

	@Inject
	private CqlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCqlParser createParser(XtextTokenStream stream) {
		return new InternalCqlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CqlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CqlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
