/* Generated By:JJTree: Do not edit this line. ASTVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniol.inf.is.odysseus.mep.impl;

public @SuppressWarnings("all")
class ASTVariable extends SimpleNode {
	public ASTVariable(int id) {
		super(id);
	}

	public ASTVariable(MEPImpl p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(MEPImplVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	private String identifier;

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getIdentifier() {
		return identifier;
	}
}
/*
 * JavaCC - OriginalChecksum=23816d72be7064594a44590879038323 (do not edit this
 * line)
 */
