/* Generated By:JJTree: Do not edit this line. ASTCorrectionMethodFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniol.inf.is.odysseus.mining.smql.parser;

public
@SuppressWarnings("all")
class ASTCorrectionMethodFunction extends SimpleNode {
  public ASTCorrectionMethodFunction(int id) {
    super(id);
  }

  public ASTCorrectionMethodFunction(SMQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=90fd485125c6574bf0c694d12b9492e8 (do not edit this line) */
