/* Generated By:JJTree: Do not edit this line. ASTCorrectionMethodMaxValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniol.inf.is.odysseus.mining.smql.parser;

public
@SuppressWarnings("all")
class ASTCorrectionMethodMaxValue extends SimpleNode {
  public ASTCorrectionMethodMaxValue(int id) {
    super(id);
  }

  public ASTCorrectionMethodMaxValue(SMQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SMQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f6bb91ac2f6953740c1a5d6f19b60ef9 (do not edit this line) */
