#!/bin/sh

mkdir -p tmp

echo "Building server"
echo "Downloading server binaries.."
wget -c http://odysseus.offis.uni-oldenburg.de/download/products/server/lastBuild/odysseus.server.gtk.linux.x86_64.zip -O tmp/odysseus.server.x86_64.zip
echo "Done."

rm -rf odysseus-server-0.1
mkdir -p odysseus-server-0.1
cd odysseus-server-0.1
mkdir -p DEBIAN
chmod 755 DEBIAN
mkdir -p usr/share
mkdir -p usr/bin

cp ../odysseus-server-control DEBIAN/control

unzip ../tmp/odysseus.server.x86_64.zip -d usr/share
mv usr/share/odysseus.server.gtk.linux.x86_64 usr/share/odysseus-server
ln -s ../share/odysseus-server/odysseus usr/bin/odysseus-server

cp -R ../etc etc

cd ..

dpkg-deb -b odysseus-server-0.1



echo "Building client"
echo "Downloading client binaries.."
wget -c http://odysseus.offis.uni-oldenburg.de/download/products/studio/lastBuild/odysseus.studio.gtk.linux.x86_64.zip -O tmp/odysseus.client.x86_64.zip
echo "Done."


rm -rf odysseus-client-0.1
mkdir -p odysseus-client-0.1
cd odysseus-client-0.1
mkdir -p DEBIAN
chmod 755 DEBIAN
mkdir -p usr/share
mkdir -p usr/bin

cp ../odysseus-client-control DEBIAN/control

unzip ../tmp/odysseus.client.x86_64.zip -d usr/share
mv usr/share/odysseus.studio.gtk.linux.x86_64 usr/share/odysseus-client
ln -s ../share/odysseus-client/studio usr/bin/odysseus-client

cd ..

dpkg-deb -b odysseus-client-0.1

echo "Building studio"
echo "Downloading studio binaries.."
wget -c http://odysseus.offis.uni-oldenburg.de/download/products/monolithic/lastBuild/odysseus.serverandstudio.gtk.linux.x86_64.zip -O tmp/odysseus.serverandstudio.x86_64.zip
echo "Done."


rm -rf odysseus-serverandstudio-0.1
mkdir -p odysseus-serverandstudio-0.1
cd odysseus-serverandstudio-0.1
mkdir -p DEBIAN
chmod 755 DEBIAN
mkdir -p usr/share
mkdir -p usr/bin

cp ../odysseus-serverandstudio-control DEBIAN/control

unzip ../tmp/odysseus.serverandstudio.x86_64.zip -d usr/share
mv usr/share/odysseus.serverandstudio.gtk.linux.x86_64 usr/share/odysseus-serverandstudio
ln -s ../share/odysseus-serverandstudio/studio usr/bin/odysseus-serverandstudio

cd ..

dpkg-deb -b odysseus-serverandstudio-0.1
