/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.uniol.inf.is.odysseus.wrapper.cameras.swig;

public class OptrisCamera {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OptrisCamera(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptrisCamera obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CameraJavaJNI.delete_OptrisCamera(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptrisCamera(String ethernetAddress) throws java.lang.RuntimeException {
    this(CameraJavaJNI.new_OptrisCamera(ethernetAddress), true);
  }

  public void start() {
    CameraJavaJNI.OptrisCamera_start(swigCPtr, this);
  }

  public void stop() {
    CameraJavaJNI.OptrisCamera_stop(swigCPtr, this);
  }

  public int getImageWidth() {
    return CameraJavaJNI.OptrisCamera_getImageWidth(swigCPtr, this);
  }

  public int getImageHeight() {
    return CameraJavaJNI.OptrisCamera_getImageHeight(swigCPtr, this);
  }

  public static void initializeSystem() throws java.lang.RuntimeException {
    CameraJavaJNI.OptrisCamera_initializeSystem();
  }

  public static void shutDownSystem() {
    CameraJavaJNI.OptrisCamera_shutDownSystem();
  }

  public static boolean isSystemInitialized() {
    return CameraJavaJNI.OptrisCamera_isSystemInitialized();
  }

}
