aggregateTIPO(operatorVariable,fastGrouping)::=<<


AggregateTIPO<ITimeInterval, IStreamObject<ITimeInterval>, IStreamObject<ITimeInterval\>> $operatorVariable$PO = new AggregateTIPO<ITimeInterval, IStreamObject<ITimeInterval>, IStreamObject<ITimeInterval\>>(
				$operatorVariable$InputSDFSchema,
				$operatorVariable$OutputSchemaInternSDFSchema,
				$operatorVariable$GroupingAttributeSDFAttributeList,
				aggregateAO.getAggregations(), $fastGrouping$, mf);


>>