;(function()
{
// CommonJS
typeof(require) != 'undefined' ? SyntaxHighlighter = require('shCore').SyntaxHighlighter : null;

function Brush()
{	
// PQL Operator
var operators =	'ACCESS ADWIN AGGREGATE APPENDTO ASSOCIATIVESTORAGE ASSUREHEARTBEAT ASSUREORDER BATCHPRODCUER BENCHMARK BENCHMARKRESULT BUFFER BUFFEREDFILTER CACHE CALCLATENCY CHANGECORRELATE CHANGEDETECT CLASSIFICATION_LEARN CLASSIFY CLUSTERING COALESCE COMPARE CONTEXTENRICH CONVERTER CONVOLUTION CSVFILESINK CSVFILESOURCE DATABASESINK DATABASESOURCE DATARATE DATARATECALC DBENRICH DETECTFACES DIFFERENCE DISTINCT DISTRIBUTION DUMMY DUPLICATEELIMINATION ELEMENTWINDOW EM ENRICH EXISTENCE EXISTENCETOPAYLOAD FASTHEATMAP FASTMEDIAN FEATUREEXTRACTION FILESINK FILTER FREQUENTPATTERN GENERATERULES GENERATOR GROUPSPLITFILEWRITER HASHFRAGMENT HDFSOURCE HEATMAP HMM HTTPSTREAMACCESS JOIN JXTABUNDLERECEIVER JXTABUNDLESENDER JXTARECEIVER JXTASENDER KALMAN KEYVALUETOTUPLE LATENCYTOPAYLOAD LEFTJOIN LINEARREGRESSION LINEARREGRESSIONMERGE LOADBALANCINGSYNCHRONIZER LOADBALANCINGTESTSENDERAO MAP MERGE PATTERN PREDICATEWINDOW PRIOIDJOIN PROBABILISTIC PROJECT PUBLISH QUALITY QUALITYINDICATOR RANGEFRAGMENT RECEIVE RECOGNIZEFACES REGRESSION RENAME REPLACEMENT REPLICATIONMERGE RETRIEVE ROUTE RRFRAGMENT SAMPLE SAMPLEFROM SASE SELECT SENDER SENTIMENTDETECTION SINK SLICEIMAGE SOCKETSINK SOMP STATEMAP STORE STOREINERTIA STOREKINECT STOREURG STREAM SUBSCRIBE SYNCHRONIZE SYNCWITHSYSTEMTIME TESTPRODUCER THROUGHPUT TIMESHIFT TIMESTAMP TIMESTAMPORDERVALIDATE TIMESTAMPTOPAYLOAD TIMEWINDOW TUPLETOKEYVALUE TWITTERSOURCE UDO UNION UNNEST VECTORQUANTIZATION VKINECTSINK WINDOW WSENRICH';

// PQL Parameter		
var parameters = 'ACTIVE ADVANCE ALGORITHM ALLOWOUTOFORDER APPEND APPENDGLOBALMEDIAN APPENDTO APPLICATIONTIMEDELAY APPLICATIONTIMEFACTOR APPLICATIONTIMEUNIT ARGUMENTS ATTR ATTRIBUTE ATTRIBUTES BATCHSIZE BUFFERTIME CACHESIZE CACHING CHARSET CLASS CLASSIFIER CLASSNAME CLEAREND COMPLETENESS CONFIDENCE CONNECTION CONNECTTOSERVER CONSISTENCY CONTINUOUS CONTROL COUNT CREATEONHEARTBEAT DATAFIELDS DATAHANDLER DATARATE DATEFORMAT DAY DB DEBBUG DEBUGCLASSIFIER DELIMITER DELIVERFIRSTELEMENT DELIVERTIME DELTA DEPENDENT DESTINATION DOMAIN DRAIN DRAINATCLOSE DRAINATDONE DROP DUMP DUMPMETADATA EACH END ENRICHATTRIBUT EXPIRATIONTIME EXPLANATORY FACTOR FASTGROUPING FETCH_ATTRIBUTES FILENAME FILETYPE FLOATINGFORMATTER FRAGMENTS FREQUENCY FUNCTION GESTURE GROUPATTRIBUTES GROUP_BY HEARTBEATRATE HIERARCHY HISTOGRAM HOST HOUR ID INCREMENTAL INDEX INIT INITIALERROR INITIALSTATE INPUTDATAHANDLER INPUTPORT INPUTSCHEMA INTERVALLENGTH ISNOOP ITEMSET ITERATIONS JDBC KEEPINPUT KEYVALUEOUTPUT LANGUAGE LAZY_CONNECTION_CHECK LEARNER LEARNINGRATE LEFT_ATTRIBUTE LEFTHIGHPREDICATE LEFTLOWPREDICATE LINENUMBERS LOCALE LOGINNEEDED MAXBUFFERSIZE MAXELEMENTS MAXELEMENTSPERGROUP MAXRESULTS MAXTIMETOWAITFORNEWEVENTMS MEASUREMENT MEASUREMENTNOISE MEMORY METHOD MILLISECOND MINIMUMSIZE MINUTE MIXTURES MODE MONTH MULTITUPLEOUTPUT NAME NEWBROKER NGRAM NGRAMUPTO NOMINALS NUMBERFORMATTER NUMCLUSTER NUMERICAL OFFSET ONECLASSIFIER ONEMATCHPERINSTANCE OPERATION OPTIONS OUTER OUTERJOIN OUTPUTDATAHANDLER OUTPUTMODE OVERLAPPINGPREDICATES PAIRS PARSINGMETHOD PARTITION PARTS PASSWORD PATH PATHS PAUSEBETWEEN PEERID PERCENTILES PIPEID PORT PREDICATE PREDICATES PREDICATETYPE PROCESSNOISE PROPERTIES PROTOCOL QUERY RANGES READFIRSTLINE REALTIMEDELAY RECALCULATE RECORDDATARATE RELATIVETOLERANCE REMOVALSTRATEGY REMOVESTOPWORDS RESULTTYPE RETURN RIGHT_ATTRIBUTE RIGHTHIGHPREDICATE RIGHTLOWPREDICATE ROUNDINGFACTOR ROUTING SAMESTARTTIME SAMPLERATE SAMPLES SCHEMA SECOND SENDALWAYSHEARTBEAT SENDINGHEARTBEATS SERVICEMETHOD SHIFT SINK SINKNAME SINKPORT SINKTYPE SIZE SIZES SLICE SLIDE SOURCE SPLITDECISION START STARTATCURRENTTIME STARTSYNCAFTER STARTTIMERAFTERFIRSTELEMENT STATISTICS STEMMWORDS STOPSYNCAFTER STORAGENAME STORE SUPPORT SUPPRESSCOUNTATTRIBUTE SYSTEMTIME TABLE TESTSETTEXT TESTSETTRUEDECISION TEXTDELIMITER TEXTTOBECLASSIFIED THREADS THRESHOLD TIME TIMEUNIT TIMEVALUE TIMEZONE TOLERANCE TOPICS TOPOLOGYTYPE TRAINSETMINSIZE TRAINSETTEXT TRAINSETTRUEDECISION TRANSACTIONS TRANSITION TRANSPORT TRIM TRUNCATE TYPE UNIQUEKEYS UNIT UPDATERATE URL URLSUFFIX USEMULTIPLE USER USEUDP VALUE VALUEATTRIBUTE VARIABLES VARIANCE WAITEACH WRAPPER WRITERESOURCEUSAGE WSDLLOCATION X XATTRIBUTE XLENGTH Y YATTRIBUTE YEAR YLENGTH';

this.regexList = [
{ regex: /\/\/\/(.*)$/gm, css: 'comments' },// comments
{ regex: SyntaxHighlighter.regexLib.multiLineDoubleQuotedString, css: 'string' },// double quoted strings
{ regex: SyntaxHighlighter.regexLib.multiLineSingleQuotedString, css: 'string' },// single quoted strings
{ regex: /\s*#.*/gm, css: 'preprocessor' },// Odysseus Script
{ regex: new RegExp(this.getKeywords(operators), 'gmi'), css: 'keyword' },// PQL operator
{ regex: new RegExp(this.getKeywords(parameters), 'gmi'), css: 'color2' }// PQL operator parameter
];
this.forHtmlScript(SyntaxHighlighter.regexLib.scriptScriptTags);
};

Brush.prototype	= new SyntaxHighlighter.Highlighter();
Brush.aliases	= ['pql', 'PQL'];
SyntaxHighlighter.brushes.Pql = Brush;
// CommonJS
typeof(exports) != 'undefined' ? exports.Brush = Brush : null;
})();
