SyntaxHighlighter.brushes.Cql = function()
{
// Copyright 2014 Christian Kuka christian@kuka.cc

// CQL keywords
var keywords =	'ADD ADVANCE ALTER ALWAYS AND ANY AS ASSIGN AT ATTACH ATTRIBUTE AUTORECONNECT AVG BROKER BY CHANNEL CHECK COMMENT CONNECTION CONTEXT COUNT CREATE DATABASE DATAHANDLER DEFAULT DELETE DETACH DISTINCT DROP EACH EXISTS FILE FROM GRANT GROUP HAVING IDENTIFIED IF IN INFTY INSERT INTERSECT INTO IS JDBC JOIN KEY KILL LAZY_CONNECTION_CHECK LIKE LINEAR_STORE LIST LOGARITHMIC_STORE LOGIN_REQUIRED MATRIX MAX MAX_ADMISSION_COST_FACTOR METADATA METRIC MIN MINUS MULTI MV NATURAL NO_LAZY_CONNECTION_CHECK NOT NULL OF OFFSET ON OPTIONS OR OUTPUT PARTITION PASSWORD PENALTY PRIORITY PROB PROTOCOL QUEUE RANGE RECORD RELATION RELATIVE REMOVE REVOKE ROLE ROWS SCOPE SELECT SENSOR SERVICELEVEL SET SILAB SINGLE SINK SIZE SLA SLIDE SOCKET STORE STREAM SUM TABLE TIME TIMEOUT TIMESENSITIV TO TRANSPORT TRUNCATE TUPLE TYPE UNBOUNDED UNION USE USER VALID VIEW WHERE WITH WRAPPER';

// CQL datatypes
var datatypes = 'ASSOCIATIONRULE BOOLEAN BYTE CLASSIFIER CORRPARTIALAGGREGATE DATE DOCUMENT DOUBLE FLOAT FREQUENTITEMSET INTEGER KEYVALUEOBJECT LONG MEDIANPARTIALAGGREGATE OBJECT PROBABILISTICBOOLEAN PROBABILISTICBYTE PROBABILISTICCONTINUOUSBYTE PROBABILISTICCONTINUOUSDOUBLE PROBABILISTICCONTINUOUSFLOAT PROBABILISTICCONTINUOUSINTEGER PROBABILISTICCONTINUOUSLONG PROBABILISTICCONTINUOUSPREDICATERESULT PROBABILISTICCONTINUOUSSHORT PROBABILISTICDOUBLE PROBABILISTICFLOAT PROBABILISTICINTEGER PROBABILISTICLONG PROBABILISTICSHORT PROBABILISTICSTRING PROBABILISTICTUPLE SHORT SPATIALGEOMETRY STDDEVPARTIALAGGREGATE STRING TIMESTAMP VECTORPROBABILISTICCONTINUOUSDOUBLE';

// Odysseus Script
var preprocessors = '#ADDQUERY #BUFFERPLACEMENT #CONFIG #DEFINE #DOQUERYSHARING #DOREWRITE #DROPALLQUERIES #DROPALLSINKS #DROPALLSOURCES #ENDIF #IF #IFDEF #IFNDEF #IFSRCDEF #IFSRCNDEF #INPUT #INCLUDE #LOGIN #LOGOUT #LOOP #METADATA #ODYSSEUS_PARAM #PRINT #PARSER #QName #QUERY #RELOADFROMLOG #RUNQUERY #SCHEDULER #SLEEP #STARTQUERIES #STARTSCHEDULER #STOPSCHEDULER #TRANSCFG #UNDEF';

this.regexList = [
{ regex: /\/\/\/(.*)$/gm, css: 'comments' },// comments
{ regex: SyntaxHighlighter.regexLib.multiLineDoubleQuotedString, css: 'string' },// double quoted strings
{ regex: SyntaxHighlighter.regexLib.multiLineSingleQuotedString, css: 'string' },// single quoted strings
{ regex: new RegExp(this.getKeywords(preprocessors), 'gm'), css: 'preprocessor' },// Odysseus Script
{ regex: new RegExp(this.getKeywords(keywords), 'gm'), css: 'color5' },// CQL keywords
{ regex: new RegExp(this.getKeywords(datatypes), 'gm'), css: 'color2' }// CQL datatypes
];
};

SyntaxHighlighter.brushes.Cql.prototype = new SyntaxHighlighter.Highlighter();
SyntaxHighlighter.brushes.Cql.aliases = ['CQL', 'cql'];
