;(function()
{
// CommonJS
typeof(require) != 'undefined' ? SyntaxHighlighter = require('shCore').SyntaxHighlighter : null;

function Brush()
{	
// PQL Operator
var operators =	'ACCESS ADWIN AGGREGATE APPENDTO ASSOCIATIVESTORAGE ASSUREHEARTBEAT ASSUREORDER AUDIENCEENGAGEMENT BATCHPRODCUER BENCHMARK BENCHMARKRESULT BUFFER BUFFEREDFILTER CACHE CALCLATENCY CHANGECORRELATE CHANGEDETECT CLASSIFICATION_LEARN CLASSIFY CLUSTERING COALESCE COMPARE CONTEXTENRICH CONVERSATIONREACH CONVERTER CONVOLUTION CSVFILESINK CSVFILESOURCE DATABASESINK DATABASESOURCE DATARATE DATARATECALC DBENRICH DETECTFACES DIFFERENCE DISTINCT DISTRIBUTION DUMMY DUPLICATEELIMINATION ELEMENTWINDOW EM ENRICH EXISTENCE EXISTENCETOPAYLOAD FASTHEATMAP FASTMEDIAN FEATUREEXTRACTION FILESINK FILTER FREQUENTPATTERN GENERATERULES GENERATOR GROUPSPLITFILEWRITER HASHFRAGMENT HDFSOURCE HEATMAP HMM HTTPSTREAMACCESS IVEFNMEACONVERTER JOIN JXTABUNDLERECEIVER JXTABUNDLESENDER JXTARECEIVER JXTASENDER KALMAN KDE KEYPERFORMANCEINDICATORS KEYVALUETOTUPLE LATENCYTOPAYLOAD LEFTJOIN LINEARREGRESSION LINEARREGRESSIONMERGE LOADBALANCINGSYNCHRONIZER LOADBALANCINGTESTRECEIVERAO LOADBALANCINGTESTSENDERAO MAP MERGE PATTERN PREDICATEWINDOW PRIOIDJOIN PROBABILISTIC PROJECT PUBLISH QUALITY QUALITYINDICATOR RANGEFRAGMENT RECEIVE RECOGNIZEFACES RECOMMENDATION RECOMMENDATION_LEARN REGRESSION RENAME REPLACEMENT REPLICATIONMERGE RETRIEVE ROUTE RRFRAGMENT SAMPLE SAMPLEFROM SASE SELECT SENDER SENTIMENTANALYSIS SENTIMENTDETECTION SHAREOFVOICE SINK SLICEIMAGE SOCKETSINK SOMP STATEMAP STORE STOREINERTIA STOREKINECT STOREURG STREAM SUBSCRIBE SYNCHRONIZE SYNCWITHSYSTEMTIME TESTPRODUCER TEXTPROCESSING THROUGHPUT TIMESHIFT TIMESTAMP TIMESTAMPORDERVALIDATE TIMESTAMPTOPAYLOAD TIMEWINDOW TUPLEAGGREGATE TUPLETOKEYVALUE TWITTERSOURCE UDO UNION UNNEST VECTORQUANTIZATION VKINECTSINK WINDOW WSENRICH';

// PQL Parameter		
var parameters = 'ACTIVE ADVANCE ALGORITHM ALLCOMPANIES ALLOWOUTOFORDER ALLTOPICS APPEND APPENDGLOBALMEDIAN APPENDTO APPLICATIONTIMEDELAY APPLICATIONTIMEFACTOR APPLICATIONTIMEUNIT ARGUMENTS ATTR ATTRIBUTE ATTRIBUTES ATTRIBUTETRAINSETTEXT ATTRIBUTETRAINSETTRUEDECISION BATCHSIZE BUFFERTIME CACHESIZE CACHING CHARSET CLASS CLASSIFIER CLASSNAME CLEAREND COMPLETENESS CONCRETETOPIC CONCRETETOPICS CONFIDENCE CONNECTION CONNECTTOSERVER CONSISTENCY CONTINUOUS CONTROL COUNT COUNTOFALLTOPICS CREATEONHEARTBEAT DATAFIELDS DATAHANDLER DATARATE DATEFORMAT DAY DB DEBUG DEBUGCLASSIFIER DELIMITER DELIVERFIRSTELEMENT DELIVERTIME DELTA DEPENDENT DESTINATION DOMAIN DONGRAM DOREMOVESTOPWORDS DOSTEMMING DRAIN DRAINATCLOSE DRAINATDONE DROP DUMP DUMPMETADATA EACH END ENRICHATTRIBUT ESCAPE_NAMES EXPIRATIONTIME EXPLANATORY FACTOR FASTGROUPING FETCH_ATTRIBUTES FILENAME FILETYPE FILTERLOADBALANCINGPUCTUATIONS FLOATINGFORMATTER FRAGMENTS FREQUENCY FUNCTION GESTURE GROUPATTRIBUTES GROUP_BY HEARTBEATRATE HIERARCHY HISTOGRAM HOST HOUR ID INCOMINGTEXT INCREMENTAL INDEX INIT INITIALERROR INITIALSTATE INPUTDATAHANDLER INPUTPORT INPUTSCHEMA INPUTTEXT INTERVALLENGTH ISNOOP ISTHERETEXTNOTTOPROCESS ITEM ITEMSET ITERATIONS IVEF IVEFTONMEA JDBC KEEPINPUT KEYVALUEOUTPUT KPINAME LANGUAGE LAZY_CONNECTION_CHECK LEARNER LEARNINGRATE LEFT_ATTRIBUTE LEFTHIGHPREDICATE LEFTLOWPREDICATE LINENUMBERS LOCALE LOGINNEEDED MAXBUFFERSIZE MAXELEMENTS MAXELEMENTSPERGROUP MAXRESULTS MAXTIMETOWAITFORNEWEVENTMS MEASUREMENT MEASUREMENTNOISE MEMORY MESSAGEDESTINATIONPEER METHOD MILLISECOND MINIMUMSIZE MINUTE MIXTURES MODE MONTH MULTITUPLEOUTPUT NAME NEWBROKER NGRAM NGRAMSIZE NGRAMUPTO NMEA NOMINALS NO_OF_RECOMMENDATIONS NUMBERFORMATTER NUMCLUSTER NUMERICAL OFFSET ONECLASSIFIER ONEMATCHPERINSTANCE OPERATION OPTIONS OUTER OUTERJOIN OUTPUTDATAHANDLER OUTPUTMODE OVERLAPPINGPREDICATES OWNCOMPANY PAIRS PARSINGMETHOD PARTITION PARTS PASSWORD PATH PATHS PAUSEBETWEEN PEERID PERCENTILES PIPEID PORT PREDICATE PREDICATES PREDICATETYPE PROCESSNOISE PROPERTIES PROTOCOL QUERY RANGES RATING READFIRSTLINE REALTIMEDELAY RECALCULATE RECOMMENDER RECORDDATARATE RELATIVETOLERANCE REMOVALSTRATEGY REMOVESTOPWORDS RESULTTYPE RETURN RIGHT_ATTRIBUTE RIGHTHIGHPREDICATE RIGHTLOWPREDICATE ROUNDINGFACTOR ROUTING SAMESTARTTIME SAMPLERATE SAMPLES SCHEMA SECOND SENDALWAYSHEARTBEAT SENDINGHEARTBEATS SERVICEMETHOD SHIFT SINK SINKNAME SINKPORT SINKTYPE SIZE SIZES SLICE SLIDE SOURCE SPLITDECISION START STARTATCURRENTTIME STARTSYNCAFTER STARTTIMERAFTERFIRSTELEMENT STATISTICS STEMMWORDS STOPSYNCAFTER STORAGENAME STORE SUBSETOFTERMS SUPPORT SUPPRESSCOUNTATTRIBUTE SYSTEMTIME TABLE TABLESCHEMA TESTSETTEXT TESTSETTRUEDECISION TEXTDELIMITER TEXTNOTTOPROCESS TEXTTOBECLASSIFIED THREADS THRESHOLD THRESHOLDVALUE TIME TIMEUNIT TIMEVALUE TIMEZONE TOLERANCE TOPICS TOPOLOGYTYPE TOTALQUANTITYOFTERMS TRAINSETMINSIZE TRAINSETTEXT TRAINSETTRUEDECISION TRANSACTIONS TRANSITION TRANSPORT TRIM TRUNCATE TYPE UNIQUEKEYS UNIT UPDATERATE URL URLSUFFIX USE_DATATYPE_MAPPINGS USEMULTIPLE USER USERIDS USEUDP VALUE VALUEATTRIBUTE VARIABLES VARIANCE WAITEACH WRAPPER WRITERESOURCEUSAGE WRITETOLOG WSDLLOCATION X XATTRIBUTE XLENGTH Y YATTRIBUTE YEAR YLENGTH';

this.regexList = [
{ regex: /\/\/\/(.*)$/gm, css: 'comments' },// comments
{ regex: SyntaxHighlighter.regexLib.multiLineDoubleQuotedString, css: 'string' },// double quoted strings
{ regex: SyntaxHighlighter.regexLib.multiLineSingleQuotedString, css: 'string' },// single quoted strings
{ regex: /\s*#.*/gm, css: 'preprocessor' },// Odysseus Script
{ regex: new RegExp(this.getKeywords(operators), 'gmi'), css: 'keyword' },// PQL operator
{ regex: new RegExp(this.getKeywords(parameters), 'gmi'), css: 'color2' }// PQL operator parameter
];
this.forHtmlScript(SyntaxHighlighter.regexLib.scriptScriptTags);
};

Brush.prototype	= new SyntaxHighlighter.Highlighter();
Brush.aliases	= ['pql', 'PQL'];
SyntaxHighlighter.brushes.Pql = Brush;
// CommonJS
typeof(exports) != 'undefined' ? exports.Brush = Brush : null;
})();
