
package de.uniol.inf.is.odysseus.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebserviceServerService", targetNamespace = "http://webservice.server.webservice.executor.planmanagement.odysseus.is.inf.uniol.de/", wsdlLocation = "http://localhost:9669/odysseus?wsdl")
public class WebserviceServerService
    extends Service
{

    private final static URL WEBSERVICESERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.uniol.inf.is.odysseus.webservice.client.WebserviceServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.uniol.inf.is.odysseus.webservice.client.WebserviceServerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9669/odysseus?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9669/odysseus?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICESERVERSERVICE_WSDL_LOCATION = url;
    }

    public WebserviceServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebserviceServerService() {
        super(WEBSERVICESERVERSERVICE_WSDL_LOCATION, new QName("http://webservice.server.webservice.executor.planmanagement.odysseus.is.inf.uniol.de/", "WebserviceServerService"));
    }

    /**
     * 
     * @return
     *     returns WebserviceServer
     */
    @WebEndpoint(name = "WebserviceServerPort")
    public WebserviceServer getWebserviceServerPort() {
        return super.getPort(new QName("http://webservice.server.webservice.executor.planmanagement.odysseus.is.inf.uniol.de/", "WebserviceServerPort"), WebserviceServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebserviceServer
     */
    @WebEndpoint(name = "WebserviceServerPort")
    public WebserviceServer getWebserviceServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.server.webservice.executor.planmanagement.odysseus.is.inf.uniol.de/", "WebserviceServerPort"), WebserviceServer.class, features);
    }

}
