/* Generated By:JJTree: Do not edit this line. ASTSimplePredicate.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package de.uniol.inf.is.odysseus.pqlhack.parser;

public class ASTSimplePredicate extends SimpleNode {
  public ASTSimplePredicate(int id) {
    super(id);
  }

  public ASTSimplePredicate(ProceduralExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ProceduralExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d38215e1fb30e95da2b893efef5d96b6 (do not edit this line) */
