/* Generated By:JJTree: Do not edit this line. ASTSlidingTimeWindow.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package de.uniol.inf.is.odysseus.pqlhack.parser;

public class ASTSlidingTimeWindow extends SimpleNode {
  public ASTSlidingTimeWindow(int id) {
    super(id);
  }

  public ASTSlidingTimeWindow(ProceduralExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ProceduralExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2501237b3de4a38daba1979d456d678e (do not edit this line) */
