/* Generated By:JavaCC: Do not edit this line. ProceduralExpressionParserTreeConstants.java Version 5.0 */
package de.uniol.inf.is.odysseus.pqlhack.parser;

public interface ProceduralExpressionParserTreeConstants
{
  public int JJTLOGICALPLAN = 0;
  public int JJTALGEBRAOP = 1;
  public int JJTTESTOP = 2;
  public int JJTPROJECTIONOP = 3;
  public int JJTPROJECTIONIDENTIFIER = 4;
  public int JJTRELATIONALPROJECTIONOP = 5;
  public int JJTSELECTIONOP = 6;
  public int JJTRELATIONALSELECTIONOP = 7;
  public int JJTRELATIONALJOINOP = 8;
  public int JJTRELATIONALNESTOP = 9;
  public int JJTRELATIONALUNNESTOP = 10;
  public int JJTJOINOP = 11;
  public int JJTWINDOWOP = 12;
  public int JJTSLIDINGTIMEWINDOW = 13;
  public int JJTTIMESTAMPATTRIBUTE = 14;
  public int JJTACCESSOP = 15;
  public int JJTBROKEROP = 16;
  public int JJTPREDICTIONASSIGNOP = 17;
  public int JJTPREDICATE = 18;
  public int JJTSIMPLEPREDICATE = 19;
  public int JJTBASICPREDICATE = 20;
  public int JJTORPREDICATE = 21;
  public int JJTANDPREDICATE = 22;
  public int JJTNOTPREDICATE = 23;
  public int JJTEXPRESSION = 24;
  public int JJTSIMPLETOKEN = 25;
  public int JJTFUNCTIONEXPRESSION = 26;
  public int JJTFUNCTIONNAME = 27;
  public int JJTNUMBER = 28;
  public int JJTSTRING = 29;
  public int JJTVOID = 30;
  public int JJTIDENTIFIER = 31;
  public int JJTCOMPAREOPERATOR = 32;
  public int JJTPREDICTIONDEFINITION = 33;
  public int JJTDEFAULTPREDICTIONDEFINITION = 34;
  public int JJTPREDICTIONFUNCTIONDEFINITION = 35;


  public String[] jjtNodeName = {
    "LogicalPlan",
    "AlgebraOp",
    "TestOp",
    "ProjectionOp",
    "ProjectionIdentifier",
    "RelationalProjectionOp",
    "SelectionOp",
    "RelationalSelectionOp",
    "RelationalJoinOp",
    "RelationalNestOp",
    "RelationalUnnestOp",
    "JoinOp",
    "WindowOp",
    "SlidingTimeWindow",
    "TimestampAttribute",
    "AccessOp",
    "BrokerOp",
    "PredictionAssignOp",
    "Predicate",
    "SimplePredicate",
    "BasicPredicate",
    "OrPredicate",
    "AndPredicate",
    "NotPredicate",
    "Expression",
    "SimpleToken",
    "FunctionExpression",
    "FunctionName",
    "Number",
    "String",
    "void",
    "Identifier",
    "CompareOperator",
    "PredictionDefinition",
    "DefaultPredictionDefinition",
    "PredictionFunctionDefinition",
  };
}
/* JavaCC - OriginalChecksum=a5d1a5e76632224de28c0a07125f5f15 (do not edit this line) */
